// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"
)

const bumpLoginChallenge = `-- name: BumpLoginChallenge :one
UPDATE login_challenges SET attempts = attempts + 1 WHERE id = ? RETURNING attempts
`

func (q *Queries) BumpLoginChallenge(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, bumpLoginChallenge, id)
	var attempts int64
	err := row.Scan(&attempts)
	return attempts, err
}

const countRecoveryCodes = `-- name: CountRecoveryCodes :one
SELECT CAST(COUNT(*) AS INTEGER) AS total,
  CAST(COALESCE(SUM(CASE WHEN used_at IS NULL THEN 1 ELSE 0 END), 0) AS INTEGER) AS unused
FROM recovery_codes WHERE user_id = ?
`

type CountRecoveryCodesRow struct {
	Total  int64
	Unused int64
}

func (q *Queries) CountRecoveryCodes(ctx context.Context, userID string) (CountRecoveryCodesRow, error) {
	row := q.db.QueryRowContext(ctx, countRecoveryCodes, userID)
	var i CountRecoveryCodesRow
	err := row.Scan(&i.Total, &i.Unused)
	return i, err
}

const createLoginChallenge = `-- name: CreateLoginChallenge :exec
INSERT INTO login_challenges (id, user_id, created_at, expires_at, attempts, ip, user_agent, next_path)
VALUES (?, ?, ?, ?, 0, ?, ?, ?)
`

type CreateLoginChallengeParams struct {
	ID        string
	UserID    string
	CreatedAt int64
	ExpiresAt int64
	Ip        string
	UserAgent string
	NextPath  string
}

func (q *Queries) CreateLoginChallenge(ctx context.Context, arg CreateLoginChallengeParams) error {
	_, err := q.db.ExecContext(ctx, createLoginChallenge,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
		arg.NextPath,
	)
	return err
}

const deleteExpiredLoginChallenges = `-- name: DeleteExpiredLoginChallenges :execrows
DELETE FROM login_challenges WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredLoginChallenges(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredLoginChallenges, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLoginChallenge = `-- name: DeleteLoginChallenge :exec
DELETE FROM login_challenges WHERE id = ?
`

func (q *Queries) DeleteLoginChallenge(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLoginChallenge, id)
	return err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :execrows
DELETE FROM sessions WHERE user_id = ? AND id != ?
`

type DeleteOtherSessionsParams struct {
	UserID string
	ID     string
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOtherSessions, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enableUserTOTP = `-- name: EnableUserTOTP :exec
UPDATE users SET totp_enabled_at = ?, totp_last_step = ? WHERE id = ?
`

type EnableUserTOTPParams struct {
	TotpEnabledAt *int64
	TotpLastStep  int64
	ID            string
}

func (q *Queries) EnableUserTOTP(ctx context.Context, arg EnableUserTOTPParams) error {
	_, err := q.db.ExecContext(ctx, enableUserTOTP, arg.TotpEnabledAt, arg.TotpLastStep, arg.ID)
	return err
}

const getLoginChallenge = `-- name: GetLoginChallenge :one
SELECT id, user_id, created_at, expires_at, attempts, ip, user_agent, next_path FROM login_challenges WHERE id = ? AND expires_at > ?
`

type GetLoginChallengeParams struct {
	ID        string
	ExpiresAt int64
}

func (q *Queries) GetLoginChallenge(ctx context.Context, arg GetLoginChallengeParams) (LoginChallenge, error) {
	row := q.db.QueryRowContext(ctx, getLoginChallenge, arg.ID, arg.ExpiresAt)
	var i LoginChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Attempts,
		&i.Ip,
		&i.UserAgent,
		&i.NextPath,
	)
	return i, err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO recovery_codes (user_id, prefix, hash, created_at) VALUES (?, ?, ?, ?)
`

type InsertRecoveryCodeParams struct {
	UserID    string
	Prefix    string
	Hash      string
	CreatedAt int64
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.ExecContext(ctx, insertRecoveryCode,
		arg.UserID,
		arg.Prefix,
		arg.Hash,
		arg.CreatedAt,
	)
	return err
}

const listRecoveryCodes = `-- name: ListRecoveryCodes :many
SELECT prefix, hash, used_at FROM recovery_codes WHERE user_id = ? ORDER BY prefix
`

type ListRecoveryCodesRow struct {
	Prefix string
	Hash   string
	UsedAt *int64
}

func (q *Queries) ListRecoveryCodes(ctx context.Context, userID string) ([]ListRecoveryCodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecoveryCodesRow
	for rows.Next() {
		var i ListRecoveryCodesRow
		if err := rows.Scan(&i.Prefix, &i.Hash, &i.UsedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, csrf, created_at, expires_at, last_project_id, user_agent, ip, last_seen_at FROM sessions WHERE user_id = ? AND expires_at > ? ORDER BY COALESCE(last_seen_at, created_at) DESC
`

type ListUserSessionsParams struct {
	UserID    string
	ExpiresAt int64
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listUserSessions, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Csrf,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastProjectID,
			&i.UserAgent,
			&i.Ip,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserTOTPLastStep = `-- name: SetUserTOTPLastStep :exec
UPDATE users SET totp_last_step = ? WHERE id = ?
`

type SetUserTOTPLastStepParams struct {
	TotpLastStep int64
	ID           string
}

func (q *Queries) SetUserTOTPLastStep(ctx context.Context, arg SetUserTOTPLastStepParams) error {
	_, err := q.db.ExecContext(ctx, setUserTOTPLastStep, arg.TotpLastStep, arg.ID)
	return err
}

const setUserTOTPSecret = `-- name: SetUserTOTPSecret :exec

UPDATE users SET totp_secret = ?, totp_enabled_at = NULL, totp_last_step = 0 WHERE id = ?
`

type SetUserTOTPSecretParams struct {
	TotpSecret *string
	ID         string
}

// Account: two-factor secrets, recovery codes, sign-in challenges and a
// person's own sessions. All keyed by user, never by org.
func (q *Queries) SetUserTOTPSecret(ctx context.Context, arg SetUserTOTPSecretParams) error {
	_, err := q.db.ExecContext(ctx, setUserTOTPSecret, arg.TotpSecret, arg.ID)
	return err
}

const useRecoveryCode = `-- name: UseRecoveryCode :execrows
UPDATE recovery_codes SET used_at = ? WHERE user_id = ? AND prefix = ? AND used_at IS NULL
`

type UseRecoveryCodeParams struct {
	UsedAt *int64
	UserID string
	Prefix string
}

func (q *Queries) UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useRecoveryCode, arg.UsedAt, arg.UserID, arg.Prefix)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
