// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_keys.sql

package db

import (
	"context"
)

const createAdminKey = `-- name: CreateAdminKey :one

INSERT INTO admin_keys (id, name, prefix, hash, access, created_by, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, prefix, hash, access, created_by, created_at, expires_at, last_used_at, last_used_ip, revoked_at
`

type CreateAdminKeyParams struct {
	ID        string
	Name      string
	Prefix    string
	Hash      string
	Access    string
	CreatedBy *string
	CreatedAt int64
	ExpiresAt int64
}

// Instance admin API keys belong to no org or project: every query here
// is instance-wide by design.
// tenancy: root
func (q *Queries) CreateAdminKey(ctx context.Context, arg CreateAdminKeyParams) (AdminKey, error) {
	row := q.db.QueryRowContext(ctx, createAdminKey,
		arg.ID,
		arg.Name,
		arg.Prefix,
		arg.Hash,
		arg.Access,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i AdminKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.Hash,
		&i.Access,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.RevokedAt,
	)
	return i, err
}

const getAdminKey = `-- name: GetAdminKey :one
SELECT id, name, prefix, hash, access, created_by, created_at, expires_at, last_used_at, last_used_ip, revoked_at FROM admin_keys WHERE id = ?
`

// tenancy: root
func (q *Queries) GetAdminKey(ctx context.Context, id string) (AdminKey, error) {
	row := q.db.QueryRowContext(ctx, getAdminKey, id)
	var i AdminKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.Hash,
		&i.Access,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.RevokedAt,
	)
	return i, err
}

const getAdminKeyState = `-- name: GetAdminKeyState :one
SELECT revoked_at, expires_at FROM admin_keys WHERE id = ?
`

type GetAdminKeyStateRow struct {
	RevokedAt *int64
	ExpiresAt int64
}

// tenancy: root (re-checks a cached key on every use)
func (q *Queries) GetAdminKeyState(ctx context.Context, id string) (GetAdminKeyStateRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminKeyState, id)
	var i GetAdminKeyStateRow
	err := row.Scan(&i.RevokedAt, &i.ExpiresAt)
	return i, err
}

const listAdminKeys = `-- name: ListAdminKeys :many
SELECT id, name, prefix, hash, access, created_by, created_at, expires_at, last_used_at, last_used_ip, revoked_at FROM admin_keys WHERE revoked_at IS NULL ORDER BY created_at DESC, id
`

// tenancy: root (keys not revoked, expired ones included)
func (q *Queries) ListAdminKeys(ctx context.Context) ([]AdminKey, error) {
	rows, err := q.db.QueryContext(ctx, listAdminKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminKey
	for rows.Next() {
		var i AdminKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.Access,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminKeysByPrefix = `-- name: ListAdminKeysByPrefix :many
SELECT id, name, prefix, hash, access, created_by, created_at, expires_at, last_used_at, last_used_ip, revoked_at FROM admin_keys WHERE prefix = ? AND revoked_at IS NULL
`

// tenancy: root (the verify path: a prefix may be shared, the hash decides)
func (q *Queries) ListAdminKeysByPrefix(ctx context.Context, prefix string) ([]AdminKey, error) {
	rows, err := q.db.QueryContext(ctx, listAdminKeysByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminKey
	for rows.Next() {
		var i AdminKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.Access,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminKeysCreatedBy = `-- name: ListAdminKeysCreatedBy :many
SELECT id, name, prefix, hash, access, created_by, created_at, expires_at, last_used_at, last_used_ip, revoked_at FROM admin_keys WHERE created_by = ? AND revoked_at IS NULL
`

// tenancy: root (the keys to revoke when their creator loses instance admin)
func (q *Queries) ListAdminKeysCreatedBy(ctx context.Context, createdBy *string) ([]AdminKey, error) {
	rows, err := q.db.QueryContext(ctx, listAdminKeysCreatedBy, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminKey
	for rows.Next() {
		var i AdminKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.Access,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAdminKey = `-- name: RevokeAdminKey :execrows
UPDATE admin_keys SET revoked_at = ? WHERE id = ? AND revoked_at IS NULL
`

type RevokeAdminKeyParams struct {
	RevokedAt *int64
	ID        string
}

// tenancy: root
func (q *Queries) RevokeAdminKey(ctx context.Context, arg RevokeAdminKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAdminKey, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAdminKey = `-- name: TouchAdminKey :exec
UPDATE admin_keys SET last_used_at = ?, last_used_ip = ? WHERE id = ?
`

type TouchAdminKeyParams struct {
	LastUsedAt *int64
	LastUsedIp *string
	ID         string
}

// tenancy: root
func (q *Queries) TouchAdminKey(ctx context.Context, arg TouchAdminKeyParams) error {
	_, err := q.db.ExecContext(ctx, touchAdminKey, arg.LastUsedAt, arg.LastUsedIp, arg.ID)
	return err
}
