// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"
)

const countAgents = `-- name: CountAgents :one
SELECT COUNT(*) FROM agents WHERE org_id = ?
`

// tenancy: org
func (q *Queries) CountAgents(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgents, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, org_id, name, token_hash, token_prefix, labels, version, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, org_id, name, token_hash, last_seen_at, version, labels, created_at, token_prefix, last_addr
`

type CreateAgentParams struct {
	ID          string
	OrgID       string
	Name        string
	TokenHash   string
	TokenPrefix string
	Labels      string
	Version     *string
	CreatedAt   int64
}

// tenancy: org
func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Labels,
		arg.Version,
		arg.CreatedAt,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeenAt,
		&i.Version,
		&i.Labels,
		&i.CreatedAt,
		&i.TokenPrefix,
		&i.LastAddr,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :execrows
DELETE FROM agents WHERE org_id = ? AND id = ?
`

type DeleteAgentParams struct {
	OrgID string
	ID    string
}

// tenancy: org
func (q *Queries) DeleteAgent(ctx context.Context, arg DeleteAgentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAgent, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAgent = `-- name: GetAgent :one
SELECT id, org_id, name, token_hash, last_seen_at, version, labels, created_at, token_prefix, last_addr FROM agents WHERE org_id = ? AND id = ?
`

type GetAgentParams struct {
	OrgID string
	ID    string
}

// tenancy: org
func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, arg.OrgID, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeenAt,
		&i.Version,
		&i.Labels,
		&i.CreatedAt,
		&i.TokenPrefix,
		&i.LastAddr,
	)
	return i, err
}

const getAgentByName = `-- name: GetAgentByName :one
SELECT id, org_id, name, token_hash, last_seen_at, version, labels, created_at, token_prefix, last_addr FROM agents WHERE org_id = ? AND name = ?
`

type GetAgentByNameParams struct {
	OrgID string
	Name  string
}

// tenancy: org
func (q *Queries) GetAgentByName(ctx context.Context, arg GetAgentByNameParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByName, arg.OrgID, arg.Name)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeenAt,
		&i.Version,
		&i.Labels,
		&i.CreatedAt,
		&i.TokenPrefix,
		&i.LastAddr,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, org_id, name, token_hash, last_seen_at, version, labels, created_at, token_prefix, last_addr FROM agents WHERE org_id = ? ORDER BY name
`

// tenancy: org
func (q *Queries) ListAgents(ctx context.Context, orgID string) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.TokenHash,
			&i.LastSeenAt,
			&i.Version,
			&i.Labels,
			&i.CreatedAt,
			&i.TokenPrefix,
			&i.LastAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByPrefix = `-- name: ListAgentsByPrefix :many
SELECT id, org_id, name, token_hash, last_seen_at, version, labels, created_at, token_prefix, last_addr FROM agents WHERE token_prefix = ?
`

// tenancy: root (bearer lookup establishes the org)
func (q *Queries) ListAgentsByPrefix(ctx context.Context, tokenPrefix string) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsByPrefix, tokenPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.TokenHash,
			&i.LastSeenAt,
			&i.Version,
			&i.Labels,
			&i.CreatedAt,
			&i.TokenPrefix,
			&i.LastAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsSeenBefore = `-- name: ListAgentsSeenBefore :many
SELECT id, org_id, name, token_hash, last_seen_at, version, labels, created_at, token_prefix, last_addr FROM agents WHERE last_seen_at IS NULL OR last_seen_at < ?
`

// tenancy: root (offline sweep, instance-wide)
func (q *Queries) ListAgentsSeenBefore(ctx context.Context, lastSeenAt *int64) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsSeenBefore, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.TokenHash,
			&i.LastSeenAt,
			&i.Version,
			&i.Labels,
			&i.CreatedAt,
			&i.TokenPrefix,
			&i.LastAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAgent = `-- name: TouchAgent :exec
UPDATE agents SET last_seen_at = ?, last_addr = ?, version = ? WHERE id = ?
`

type TouchAgentParams struct {
	LastSeenAt *int64
	LastAddr   *string
	Version    *string
	ID         string
}

// tenancy: root (the gateway acts for a verified agent)
func (q *Queries) TouchAgent(ctx context.Context, arg TouchAgentParams) error {
	_, err := q.db.ExecContext(ctx, touchAgent,
		arg.LastSeenAt,
		arg.LastAddr,
		arg.Version,
		arg.ID,
	)
	return err
}

const updateAgentLabels = `-- name: UpdateAgentLabels :one
UPDATE agents SET labels = ? WHERE org_id = ? AND id = ? RETURNING id, org_id, name, token_hash, last_seen_at, version, labels, created_at, token_prefix, last_addr
`

type UpdateAgentLabelsParams struct {
	Labels string
	OrgID  string
	ID     string
}

// tenancy: org
func (q *Queries) UpdateAgentLabels(ctx context.Context, arg UpdateAgentLabelsParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, updateAgentLabels, arg.Labels, arg.OrgID, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenHash,
		&i.LastSeenAt,
		&i.Version,
		&i.Labels,
		&i.CreatedAt,
		&i.TokenPrefix,
		&i.LastAddr,
	)
	return i, err
}
