// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, project_id, org_id, name, prefix, hash, access, created_by, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, org_id, name, prefix, hash, access, created_by, created_at, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	ID        string
	ProjectID *string
	OrgID     string
	Name      string
	Prefix    string
	Hash      string
	Access    string
	CreatedBy *string
	CreatedAt int64
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.ID,
		arg.ProjectID,
		arg.OrgID,
		arg.Name,
		arg.Prefix,
		arg.Hash,
		arg.Access,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.Prefix,
		&i.Hash,
		&i.Access,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, project_id, org_id, name, prefix, hash, access, created_by, created_at, last_used_at, revoked_at FROM api_keys WHERE project_id = ? AND id = ?
`

type GetAPIKeyParams struct {
	ProjectID *string
	ID        string
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKey, arg.ProjectID, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.Prefix,
		&i.Hash,
		&i.Access,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, project_id, org_id, name, prefix, hash, access, created_by, created_at, last_used_at, revoked_at FROM api_keys WHERE project_id = ? AND revoked_at IS NULL ORDER BY created_at
`

func (q *Queries) ListAPIKeys(ctx context.Context, projectID *string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OrgID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.Access,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByPrefix = `-- name: ListAPIKeysByPrefix :many
SELECT id, project_id, org_id, name, prefix, hash, access, created_by, created_at, last_used_at, revoked_at FROM api_keys WHERE prefix = ? AND revoked_at IS NULL
`

// tenancy: root (bearer lookup establishes the scope)
func (q *Queries) ListAPIKeysByPrefix(ctx context.Context, prefix string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OrgID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.Access,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgAPIKeys = `-- name: ListOrgAPIKeys :many
SELECT id, project_id, org_id, name, prefix, hash, access, created_by, created_at, last_used_at, revoked_at FROM api_keys WHERE org_id = ? AND project_id IS NULL AND revoked_at IS NULL ORDER BY created_at
`

// tenancy: org (org keys have no project)
func (q *Queries) ListOrgAPIKeys(ctx context.Context, orgID string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listOrgAPIKeys, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OrgID,
			&i.Name,
			&i.Prefix,
			&i.Hash,
			&i.Access,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = ? WHERE project_id = ? AND id = ? AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	RevokedAt *int64
	ProjectID *string
	ID        string
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAPIKey, arg.RevokedAt, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeOrgAPIKey = `-- name: RevokeOrgAPIKey :execrows
UPDATE api_keys SET revoked_at = ? WHERE org_id = ? AND project_id IS NULL AND id = ? AND revoked_at IS NULL
`

type RevokeOrgAPIKeyParams struct {
	RevokedAt *int64
	OrgID     string
	ID        string
}

// tenancy: org (org keys have no project)
func (q *Queries) RevokeOrgAPIKey(ctx context.Context, arg RevokeOrgAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeOrgAPIKey, arg.RevokedAt, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = ? WHERE id = ?
`

type TouchAPIKeyParams struct {
	LastUsedAt *int64
	ID         string
}

// tenancy: root (called after the key was verified)
func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIKey, arg.LastUsedAt, arg.ID)
	return err
}
