// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const countAudit = `-- name: CountAudit :one
SELECT
  CAST(COALESCE(SUM(CASE WHEN act LIKE 'user.%' OR act LIKE 'member.%' OR act LIKE 'invite.%' OR act LIKE '%key.%' THEN 1 ELSE 0 END), 0) AS INTEGER) AS access,
  CAST(COALESCE(SUM(CASE WHEN act LIKE 'user.%' OR act LIKE 'member.%' OR act LIKE 'invite.%' OR act LIKE '%key.%' THEN 0 ELSE 1 END), 0) AS INTEGER) AS changes
FROM audit a
WHERE (?1 = '' OR a.org_id = ?1 OR (a.org_id IS NULL AND a.act LIKE 'user.sign%' AND a.target IN (SELECT u.subject FROM users u JOIN memberships m ON m.user_id = u.id WHERE m.org_id = ?1)))
  AND (?2 = '' OR a.project_id = ?2)
  AND (?3 = 0 OR a.project_id IS NULL)
  AND (?4 = 0 OR project_id IS NOT NULL)
  AND at >= ?5
`

type CountAuditParams struct {
	OrgID       interface{}
	ProjectID   interface{}
	OrgOnly     interface{}
	ProjectOnly interface{}
	Since       int64
}

type CountAuditRow struct {
	Access  int64
	Changes int64
}

// tenancy: root (the service scopes by org_id and project_id)
func (q *Queries) CountAudit(ctx context.Context, arg CountAuditParams) (CountAuditRow, error) {
	row := q.db.QueryRowContext(ctx, countAudit,
		arg.OrgID,
		arg.ProjectID,
		arg.OrgOnly,
		arg.ProjectOnly,
		arg.Since,
	)
	var i CountAuditRow
	err := row.Scan(&i.Access, &i.Changes)
	return i, err
}

const countStateEvents = `-- name: CountStateEvents :one
SELECT COUNT(*) FROM events e JOIN projects p ON p.id = e.project_id
WHERE (?1 = '' OR p.org_id = ?1)
  AND (?2 = '' OR e.project_id = ?2)
  AND e.at >= ?3
`

type CountStateEventsParams struct {
	OrgID     interface{}
	ProjectID interface{}
	Since     int64
}

// tenancy: root (the service scopes by org_id and project_id)
func (q *Queries) CountStateEvents(ctx context.Context, arg CountStateEventsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStateEvents, arg.OrgID, arg.ProjectID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getInstanceMeta = `-- name: GetInstanceMeta :one
SELECT name, value, updated_at FROM instance_meta WHERE name = ?
`

// tenancy: root (instance facts)
func (q *Queries) GetInstanceMeta(ctx context.Context, name string) (InstanceMetum, error) {
	row := q.db.QueryRowContext(ctx, getInstanceMeta, name)
	var i InstanceMetum
	err := row.Scan(&i.Name, &i.Value, &i.UpdatedAt)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit (id, at, actor, actor_kind, actor_id, org_id, project_id, act, target, target_id, spec_before, spec_after, detail, via, request_id, remote_addr)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16)
`

type InsertAuditParams struct {
	ID         string
	At         int64
	Actor      string
	ActorKind  string
	ActorID    *string
	OrgID      *string
	ProjectID  *string
	Act        string
	Target     string
	TargetID   *string
	SpecBefore *string
	SpecAfter  *string
	Detail     string
	Via        string
	RequestID  *string
	RemoteAddr *string
}

// tenancy: root (written inside the transaction of the action, for its scope)
func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAudit,
		arg.ID,
		arg.At,
		arg.Actor,
		arg.ActorKind,
		arg.ActorID,
		arg.OrgID,
		arg.ProjectID,
		arg.Act,
		arg.Target,
		arg.TargetID,
		arg.SpecBefore,
		arg.SpecAfter,
		arg.Detail,
		arg.Via,
		arg.RequestID,
		arg.RemoteAddr,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT a.id, a.at, 'audit' AS source, a.actor, a.actor_kind, a.actor_id, a.org_id, a.project_id, a.act, a.target, a.target_id, a.spec_before, a.spec_after, a.detail, a.via, a.request_id, a.remote_addr
FROM audit a
WHERE (?1 = '' OR a.org_id = ?1 OR (a.org_id IS NULL AND a.act LIKE 'user.sign%' AND a.target IN (SELECT u.subject FROM users u JOIN memberships m ON m.user_id = u.id WHERE m.org_id = ?1)))
  AND (?2 = '' OR a.project_id = ?2)
  AND (?3 = 0 OR a.project_id IS NULL)
  AND (?4 = 0 OR a.project_id IS NOT NULL)
  AND (?5 = '' OR a.actor = ?5)
  AND a.at >= ?6
  AND (a.at < ?7 OR (a.at = ?7 AND a.id < ?8))
  AND ((?9 = 1 AND NOT (a.act LIKE 'user.%' OR a.act LIKE 'member.%' OR a.act LIKE 'invite.%' OR a.act LIKE '%key.%'))
    OR (?10 = 1 AND (a.act LIKE 'user.%' OR a.act LIKE 'member.%' OR a.act LIKE 'invite.%' OR a.act LIKE '%key.%')))
UNION ALL
SELECT e.id, e.at, 'event' AS source, 'vink' AS actor, 'system' AS actor_kind, NULL AS actor_id, p.org_id, e.project_id, 'state.' || e.to_state AS act, m.slug AS target, m.id AS target_id,
  NULL AS spec_before, NULL AS spec_after, json_object('from', e.from_state, 'reason', e.reason) AS detail,
  CASE WHEN o.source IS NULL THEN 'vink' WHEN o.source = 'local' THEN 'checker' WHEN o.source LIKE 'agent:%' THEN o.source ELSE 'ping' END AS via,
  NULL AS request_id, NULL AS remote_addr
FROM events e JOIN monitors m ON m.id = e.monitor_id JOIN projects p ON p.id = e.project_id LEFT JOIN observations o ON o.id = e.observation_id
WHERE ?11 = 1 AND ?3 = 0
  AND (?1 = '' OR p.org_id = ?1)
  AND (?2 = '' OR e.project_id = ?2)
  AND ?5 = ''
  AND e.at >= ?6
  AND (e.at < ?7 OR (e.at = ?7 AND e.id < ?8))
ORDER BY 2 DESC, 1 DESC
LIMIT 51
`

type ListAuditParams struct {
	OrgID       interface{}
	ProjectID   interface{}
	OrgOnly     interface{}
	ProjectOnly interface{}
	Actor       interface{}
	Since       int64
	BeforeAt    int64
	BeforeID    string
	Changes     interface{}
	Access      interface{}
	State       interface{}
}

type ListAuditRow struct {
	ID         string
	At         int64
	Source     string
	Actor      string
	ActorKind  string
	ActorID    *string
	OrgID      *string
	ProjectID  *string
	Act        string
	Target     string
	TargetID   *string
	SpecBefore *string
	SpecAfter  *string
	Detail     string
	Via        string
	RequestID  *string
	RemoteAddr *string
}

// tenancy: root (the service scopes by org_id and project_id below)
// The log: admin actions from audit and state flips from events, newest
// first, 51 rows so the caller knows whether an older page exists. Sign-ins
// carry no org; an org's log shows those of its members.
func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]ListAuditRow, error) {
	rows, err := q.db.QueryContext(ctx, listAudit,
		arg.OrgID,
		arg.ProjectID,
		arg.OrgOnly,
		arg.ProjectOnly,
		arg.Actor,
		arg.Since,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Changes,
		arg.Access,
		arg.State,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditRow
	for rows.Next() {
		var i ListAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Source,
			&i.Actor,
			&i.ActorKind,
			&i.ActorID,
			&i.OrgID,
			&i.ProjectID,
			&i.Act,
			&i.Target,
			&i.TargetID,
			&i.SpecBefore,
			&i.SpecAfter,
			&i.Detail,
			&i.Via,
			&i.RequestID,
			&i.RemoteAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditActors = `-- name: ListAuditActors :many
SELECT DISTINCT a.actor FROM audit a
WHERE (?1 = '' OR a.org_id = ?1 OR (a.org_id IS NULL AND a.act LIKE 'user.sign%' AND a.target IN (SELECT u.subject FROM users u JOIN memberships m ON m.user_id = u.id WHERE m.org_id = ?1)))
  AND (?2 = '' OR a.project_id = ?2)
  AND at >= ?3
ORDER BY actor
`

type ListAuditActorsParams struct {
	OrgID     interface{}
	ProjectID interface{}
	Since     int64
}

// tenancy: root (the service scopes by org_id and project_id)
func (q *Queries) ListAuditActors(ctx context.Context, arg ListAuditActorsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAuditActors, arg.OrgID, arg.ProjectID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var actor string
		if err := rows.Scan(&actor); err != nil {
			return nil, err
		}
		items = append(items, actor)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInstanceMeta = `-- name: SetInstanceMeta :exec
INSERT INTO instance_meta (name, value, updated_at) VALUES (?, ?, ?)
ON CONFLICT (name) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type SetInstanceMetaParams struct {
	Name      string
	Value     string
	UpdatedAt int64
}

// tenancy: root (instance facts)
func (q *Queries) SetInstanceMeta(ctx context.Context, arg SetInstanceMetaParams) error {
	_, err := q.db.ExecContext(ctx, setInstanceMeta, arg.Name, arg.Value, arg.UpdatedAt)
	return err
}
