// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bodies.sql

package db

import (
	"context"
)

const deleteBodiesBefore = `-- name: DeleteBodiesBefore :execrows
DELETE FROM bodies WHERE created_at < ?
`

// tenancy: root (retention job)
func (q *Queries) DeleteBodiesBefore(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBodiesBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBody = `-- name: GetBody :one
SELECT observation_id, project_id, content, content_type, created_at FROM bodies WHERE project_id = ? AND observation_id = ?
`

type GetBodyParams struct {
	ProjectID     string
	ObservationID string
}

func (q *Queries) GetBody(ctx context.Context, arg GetBodyParams) (Body, error) {
	row := q.db.QueryRowContext(ctx, getBody, arg.ProjectID, arg.ObservationID)
	var i Body
	err := row.Scan(
		&i.ObservationID,
		&i.ProjectID,
		&i.Content,
		&i.ContentType,
		&i.CreatedAt,
	)
	return i, err
}

const insertBody = `-- name: InsertBody :exec
INSERT INTO bodies (observation_id, project_id, content, content_type, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertBodyParams struct {
	ObservationID string
	ProjectID     string
	Content       []byte
	ContentType   string
	CreatedAt     int64
}

func (q *Queries) InsertBody(ctx context.Context, arg InsertBodyParams) error {
	_, err := q.db.ExecContext(ctx, insertBody,
		arg.ObservationID,
		arg.ProjectID,
		arg.Content,
		arg.ContentType,
		arg.CreatedAt,
	)
	return err
}
