// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (id, project_id, org_id, name, kind, config, enabled, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, org_id, name, kind, config, enabled, created_at, updated_at
`

type CreateChannelParams struct {
	ID        string
	ProjectID *string
	OrgID     string
	Name      string
	Kind      string
	Config    string
	Enabled   bool
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel,
		arg.ID,
		arg.ProjectID,
		arg.OrgID,
		arg.Name,
		arg.Kind,
		arg.Config,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE FROM channels WHERE project_id = ? AND id = ?
`

type DeleteChannelParams struct {
	ProjectID *string
	ID        string
}

func (q *Queries) DeleteChannel(ctx context.Context, arg DeleteChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteChannel, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOrgChannel = `-- name: DeleteOrgChannel :execrows
DELETE FROM channels WHERE org_id = ? AND project_id IS NULL AND id = ?
`

type DeleteOrgChannelParams struct {
	OrgID string
	ID    string
}

// tenancy: org
func (q *Queries) DeleteOrgChannel(ctx context.Context, arg DeleteOrgChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrgChannel, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getChannel = `-- name: GetChannel :one
SELECT id, project_id, org_id, name, kind, config, enabled, created_at, updated_at FROM channels WHERE project_id = ? AND id = ?
`

type GetChannelParams struct {
	ProjectID *string
	ID        string
}

func (q *Queries) GetChannel(ctx context.Context, arg GetChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, arg.ProjectID, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByName = `-- name: GetChannelByName :one
SELECT id, project_id, org_id, name, kind, config, enabled, created_at, updated_at FROM channels WHERE project_id = ? AND name = ?
`

type GetChannelByNameParams struct {
	ProjectID *string
	Name      string
}

func (q *Queries) GetChannelByName(ctx context.Context, arg GetChannelByNameParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByName, arg.ProjectID, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgChannel = `-- name: GetOrgChannel :one
SELECT id, project_id, org_id, name, kind, config, enabled, created_at, updated_at FROM channels WHERE org_id = ? AND project_id IS NULL AND id = ?
`

type GetOrgChannelParams struct {
	OrgID string
	ID    string
}

// tenancy: org (a channel of the org itself, project_id NULL)
func (q *Queries) GetOrgChannel(ctx context.Context, arg GetOrgChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getOrgChannel, arg.OrgID, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, project_id, org_id, name, kind, config, enabled, created_at, updated_at FROM channels WHERE project_id = ? ORDER BY name
`

func (q *Queries) ListChannels(ctx context.Context, projectID *string) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OrgID,
			&i.Name,
			&i.Kind,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgChannels = `-- name: ListOrgChannels :many
SELECT id, project_id, org_id, name, kind, config, enabled, created_at, updated_at FROM channels WHERE org_id = ? AND project_id IS NULL ORDER BY name
`

// tenancy: org
func (q *Queries) ListOrgChannels(ctx context.Context, orgID string) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listOrgChannels, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OrgID,
			&i.Name,
			&i.Kind,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelEnabled = `-- name: SetChannelEnabled :one
UPDATE channels
SET enabled = ?, updated_at = ?
WHERE project_id = ? AND id = ?
RETURNING id, project_id, org_id, name, kind, config, enabled, created_at, updated_at
`

type SetChannelEnabledParams struct {
	Enabled   bool
	UpdatedAt int64
	ProjectID *string
	ID        string
}

func (q *Queries) SetChannelEnabled(ctx context.Context, arg SetChannelEnabledParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, setChannelEnabled,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setOrgChannelEnabled = `-- name: SetOrgChannelEnabled :one
UPDATE channels
SET enabled = ?, updated_at = ?
WHERE org_id = ? AND project_id IS NULL AND id = ?
RETURNING id, project_id, org_id, name, kind, config, enabled, created_at, updated_at
`

type SetOrgChannelEnabledParams struct {
	Enabled   bool
	UpdatedAt int64
	OrgID     string
	ID        string
}

// tenancy: org
func (q *Queries) SetOrgChannelEnabled(ctx context.Context, arg SetOrgChannelEnabledParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, setOrgChannelEnabled,
		arg.Enabled,
		arg.UpdatedAt,
		arg.OrgID,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name = ?, kind = ?, config = ?, enabled = ?, updated_at = ?
WHERE project_id = ? AND id = ?
RETURNING id, project_id, org_id, name, kind, config, enabled, created_at, updated_at
`

type UpdateChannelParams struct {
	Name      string
	Kind      string
	Config    string
	Enabled   bool
	UpdatedAt int64
	ProjectID *string
	ID        string
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, updateChannel,
		arg.Name,
		arg.Kind,
		arg.Config,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrgChannel = `-- name: UpdateOrgChannel :one
UPDATE channels
SET name = ?, kind = ?, config = ?, enabled = ?, updated_at = ?
WHERE org_id = ? AND project_id IS NULL AND id = ?
RETURNING id, project_id, org_id, name, kind, config, enabled, created_at, updated_at
`

type UpdateOrgChannelParams struct {
	Name      string
	Kind      string
	Config    string
	Enabled   bool
	UpdatedAt int64
	OrgID     string
	ID        string
}

// tenancy: org
func (q *Queries) UpdateOrgChannel(ctx context.Context, arg UpdateOrgChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, updateOrgChannel,
		arg.Name,
		arg.Kind,
		arg.Config,
		arg.Enabled,
		arg.UpdatedAt,
		arg.OrgID,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
