// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package db

import (
	"context"
)

const countEarlierPendingDeliveries = `-- name: CountEarlierPendingDeliveries :one
SELECT COUNT(*) FROM deliveries
WHERE monitor_id = ? AND channel_id = ? AND delivered_at IS NULL AND failed_at IS NULL AND created_at < ?
`

type CountEarlierPendingDeliveriesParams struct {
	MonitorID string
	ChannelID string
	CreatedAt int64
}

// tenancy: root (dispatcher keeps per-monitor order)
func (q *Queries) CountEarlierPendingDeliveries(ctx context.Context, arg CountEarlierPendingDeliveriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEarlierPendingDeliveries, arg.MonitorID, arg.ChannelID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingDeliveries = `-- name: CountPendingDeliveries :one
SELECT COUNT(*) FROM deliveries WHERE delivered_at IS NULL AND failed_at IS NULL
`

// tenancy: root (metrics endpoint)
func (q *Queries) CountPendingDeliveries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingDeliveries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertDelivery = `-- name: InsertDelivery :exec
INSERT INTO deliveries (id, event_id, channel_id, project_id, monitor_id, route_id, kind, repeat, attempt, next_attempt_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDeliveryParams struct {
	ID            string
	EventID       string
	ChannelID     string
	ProjectID     string
	MonitorID     string
	RouteID       *string
	Kind          string
	Repeat        bool
	Attempt       int64
	NextAttemptAt int64
	CreatedAt     int64
}

func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, insertDelivery,
		arg.ID,
		arg.EventID,
		arg.ChannelID,
		arg.ProjectID,
		arg.MonitorID,
		arg.RouteID,
		arg.Kind,
		arg.Repeat,
		arg.Attempt,
		arg.NextAttemptAt,
		arg.CreatedAt,
	)
	return err
}

const lastDeliveryForRoute = `-- name: LastDeliveryForRoute :one
SELECT id, event_id, channel_id, project_id, monitor_id, route_id, kind, repeat, attempt, next_attempt_at, delivered_at, failed_at, error, created_at FROM deliveries
WHERE monitor_id = ? AND route_id = ?
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type LastDeliveryForRouteParams struct {
	MonitorID string
	RouteID   *string
}

// tenancy: root (dispatcher, repeat_every)
func (q *Queries) LastDeliveryForRoute(ctx context.Context, arg LastDeliveryForRouteParams) (Delivery, error) {
	row := q.db.QueryRowContext(ctx, lastDeliveryForRoute, arg.MonitorID, arg.RouteID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ChannelID,
		&i.ProjectID,
		&i.MonitorID,
		&i.RouteID,
		&i.Kind,
		&i.Repeat,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const lastSentForChannel = `-- name: LastSentForChannel :one
SELECT CAST(COALESCE(MAX(delivered_at), 0) AS INTEGER) AS last_sent
FROM deliveries WHERE project_id = ? AND channel_id = ? AND delivered_at IS NOT NULL
`

type LastSentForChannelParams struct {
	ProjectID string
	ChannelID string
}

func (q *Queries) LastSentForChannel(ctx context.Context, arg LastSentForChannelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastSentForChannel, arg.ProjectID, arg.ChannelID)
	var last_sent int64
	err := row.Scan(&last_sent)
	return last_sent, err
}

const listDeliveriesForEvent = `-- name: ListDeliveriesForEvent :many
SELECT id, event_id, channel_id, project_id, monitor_id, route_id, kind, repeat, attempt, next_attempt_at, delivered_at, failed_at, error, created_at FROM deliveries WHERE project_id = ? AND event_id = ? ORDER BY created_at, id
`

type ListDeliveriesForEventParams struct {
	ProjectID string
	EventID   string
}

func (q *Queries) ListDeliveriesForEvent(ctx context.Context, arg ListDeliveriesForEventParams) ([]Delivery, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveriesForEvent, arg.ProjectID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ChannelID,
			&i.ProjectID,
			&i.MonitorID,
			&i.RouteID,
			&i.Kind,
			&i.Repeat,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueDeliveries = `-- name: ListDueDeliveries :many
SELECT id, event_id, channel_id, project_id, monitor_id, route_id, kind, repeat, attempt, next_attempt_at, delivered_at, failed_at, error, created_at FROM deliveries
WHERE delivered_at IS NULL AND failed_at IS NULL AND next_attempt_at <= ?
ORDER BY next_attempt_at, created_at, id
LIMIT ?
`

type ListDueDeliveriesParams struct {
	NextAttemptAt int64
	Limit         int64
}

// tenancy: root (dispatcher)
func (q *Queries) ListDueDeliveries(ctx context.Context, arg ListDueDeliveriesParams) ([]Delivery, error) {
	rows, err := q.db.QueryContext(ctx, listDueDeliveries, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ChannelID,
			&i.ProjectID,
			&i.MonitorID,
			&i.RouteID,
			&i.Kind,
			&i.Repeat,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeliveries = `-- name: ListRecentDeliveries :many
SELECT d.id, d.event_id, d.channel_id, d.project_id, d.monitor_id, d.route_id, d.kind, d.repeat, d.attempt, d.next_attempt_at, d.delivered_at, d.failed_at, d.error, d.created_at, c.name AS channel_name, c.kind AS channel_kind
FROM deliveries d JOIN channels c ON c.id = d.channel_id
WHERE d.project_id = ?
ORDER BY d.created_at DESC, d.id DESC
LIMIT ?
`

type ListRecentDeliveriesParams struct {
	ProjectID string
	Limit     int64
}

type ListRecentDeliveriesRow struct {
	ID            string
	EventID       string
	ChannelID     string
	ProjectID     string
	MonitorID     string
	RouteID       *string
	Kind          string
	Repeat        bool
	Attempt       int64
	NextAttemptAt int64
	DeliveredAt   *int64
	FailedAt      *int64
	Error         *string
	CreatedAt     int64
	ChannelName   string
	ChannelKind   string
}

func (q *Queries) ListRecentDeliveries(ctx context.Context, arg ListRecentDeliveriesParams) ([]ListRecentDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentDeliveries, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentDeliveriesRow
	for rows.Next() {
		var i ListRecentDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ChannelID,
			&i.ProjectID,
			&i.MonitorID,
			&i.RouteID,
			&i.Kind,
			&i.Repeat,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.Error,
			&i.CreatedAt,
			&i.ChannelName,
			&i.ChannelKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryDelivered = `-- name: MarkDeliveryDelivered :exec
UPDATE deliveries SET delivered_at = ?, attempt = ?, error = NULL WHERE id = ?
`

type MarkDeliveryDeliveredParams struct {
	DeliveredAt *int64
	Attempt     int64
	ID          string
}

// tenancy: root (dispatcher)
func (q *Queries) MarkDeliveryDelivered(ctx context.Context, arg MarkDeliveryDeliveredParams) error {
	_, err := q.db.ExecContext(ctx, markDeliveryDelivered, arg.DeliveredAt, arg.Attempt, arg.ID)
	return err
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :exec
UPDATE deliveries SET attempt = ?, failed_at = ?, error = ? WHERE id = ?
`

type MarkDeliveryFailedParams struct {
	Attempt  int64
	FailedAt *int64
	Error    *string
	ID       string
}

// tenancy: root (dispatcher)
func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error {
	_, err := q.db.ExecContext(ctx, markDeliveryFailed,
		arg.Attempt,
		arg.FailedAt,
		arg.Error,
		arg.ID,
	)
	return err
}

const rescheduleDelivery = `-- name: RescheduleDelivery :exec
UPDATE deliveries SET attempt = ?, next_attempt_at = ?, error = ? WHERE id = ?
`

type RescheduleDeliveryParams struct {
	Attempt       int64
	NextAttemptAt int64
	Error         *string
	ID            string
}

// tenancy: root (dispatcher)
func (q *Queries) RescheduleDelivery(ctx context.Context, arg RescheduleDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, rescheduleDelivery,
		arg.Attempt,
		arg.NextAttemptAt,
		arg.Error,
		arg.ID,
	)
	return err
}
