// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
)

const getEvent = `-- name: GetEvent :one
SELECT id, monitor_id, project_id, at, from_state, to_state, reason, observation_id FROM events WHERE project_id = ? AND id = ?
`

type GetEventParams struct {
	ProjectID string
	ID        string
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, arg.ProjectID, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ProjectID,
		&i.At,
		&i.FromState,
		&i.ToState,
		&i.Reason,
		&i.ObservationID,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (id, monitor_id, project_id, at, from_state, to_state, reason, observation_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	ID            string
	MonitorID     string
	ProjectID     string
	At            int64
	FromState     string
	ToState       string
	Reason        string
	ObservationID *string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.MonitorID,
		arg.ProjectID,
		arg.At,
		arg.FromState,
		arg.ToState,
		arg.Reason,
		arg.ObservationID,
	)
	return err
}

const listEvents = `-- name: ListEvents :many
SELECT id, monitor_id, project_id, at, from_state, to_state, reason, observation_id FROM events
WHERE project_id = ? AND monitor_id = ?
ORDER BY at DESC, id DESC
LIMIT ?
`

type ListEventsParams struct {
	ProjectID string
	MonitorID string
	Limit     int64
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.ProjectID, arg.MonitorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.ProjectID,
			&i.At,
			&i.FromState,
			&i.ToState,
			&i.Reason,
			&i.ObservationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsSince = `-- name: ListEventsSince :many
SELECT id, monitor_id, project_id, at, from_state, to_state, reason, observation_id FROM events
WHERE project_id = ? AND monitor_id = ? AND at >= ?
ORDER BY at, id
`

type ListEventsSinceParams struct {
	ProjectID string
	MonitorID string
	At        int64
}

func (q *Queries) ListEventsSince(ctx context.Context, arg ListEventsSinceParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsSince, arg.ProjectID, arg.MonitorID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.ProjectID,
			&i.At,
			&i.FromState,
			&i.ToState,
			&i.Reason,
			&i.ObservationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectEvents = `-- name: ListProjectEvents :many
SELECT e.id, e.monitor_id, e.project_id, e.at, e.from_state, e.to_state, e.reason, e.observation_id, m.slug AS monitor_slug, m.name AS monitor_name
FROM events e JOIN monitors m ON m.id = e.monitor_id
WHERE e.project_id = ?
ORDER BY e.at DESC, e.id DESC
LIMIT ?
`

type ListProjectEventsParams struct {
	ProjectID string
	Limit     int64
}

type ListProjectEventsRow struct {
	ID            string
	MonitorID     string
	ProjectID     string
	At            int64
	FromState     string
	ToState       string
	Reason        string
	ObservationID *string
	MonitorSlug   string
	MonitorName   string
}

func (q *Queries) ListProjectEvents(ctx context.Context, arg ListProjectEventsParams) ([]ListProjectEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectEvents, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectEventsRow
	for rows.Next() {
		var i ListProjectEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.ProjectID,
			&i.At,
			&i.FromState,
			&i.ToState,
			&i.Reason,
			&i.ObservationID,
			&i.MonitorSlug,
			&i.MonitorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
