// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package db

import (
	"context"
)

const ackIncident = `-- name: AckIncident :execrows
UPDATE incidents SET acked_by = ?, acked_at = ?
WHERE project_id = ? AND id = ? AND acked_at IS NULL AND resolved_at IS NULL
`

type AckIncidentParams struct {
	AckedBy   *string
	AckedAt   *int64
	ProjectID string
	ID        string
}

func (q *Queries) AckIncident(ctx context.Context, arg AckIncidentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, ackIncident,
		arg.AckedBy,
		arg.AckedAt,
		arg.ProjectID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countOpenIncidents = `-- name: CountOpenIncidents :one
SELECT COUNT(*) FROM incidents WHERE project_id = ? AND resolved_at IS NULL
`

func (q *Queries) CountOpenIncidents(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenIncidents, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getIncident = `-- name: GetIncident :one
SELECT i.id, i.monitor_id, i.project_id, i.opened_at, i.resolved_at, i.acked_by, i.acked_at, i.open_event_id, i.close_event_id, COALESCE(e.reason, '') AS reason
FROM incidents i LEFT JOIN events e ON e.id = i.open_event_id
WHERE i.project_id = ? AND i.id = ?
`

type GetIncidentParams struct {
	ProjectID string
	ID        string
}

type GetIncidentRow struct {
	ID           string
	MonitorID    string
	ProjectID    string
	OpenedAt     int64
	ResolvedAt   *int64
	AckedBy      *string
	AckedAt      *int64
	OpenEventID  string
	CloseEventID *string
	Reason       string
}

func (q *Queries) GetIncident(ctx context.Context, arg GetIncidentParams) (GetIncidentRow, error) {
	row := q.db.QueryRowContext(ctx, getIncident, arg.ProjectID, arg.ID)
	var i GetIncidentRow
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ProjectID,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.AckedBy,
		&i.AckedAt,
		&i.OpenEventID,
		&i.CloseEventID,
		&i.Reason,
	)
	return i, err
}

const getOpenIncidentForMonitor = `-- name: GetOpenIncidentForMonitor :one
SELECT id, monitor_id, project_id, opened_at, resolved_at, acked_by, acked_at, open_event_id, close_event_id FROM incidents
WHERE project_id = ? AND monitor_id = ? AND resolved_at IS NULL
ORDER BY opened_at DESC
LIMIT 1
`

type GetOpenIncidentForMonitorParams struct {
	ProjectID string
	MonitorID string
}

func (q *Queries) GetOpenIncidentForMonitor(ctx context.Context, arg GetOpenIncidentForMonitorParams) (Incident, error) {
	row := q.db.QueryRowContext(ctx, getOpenIncidentForMonitor, arg.ProjectID, arg.MonitorID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ProjectID,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.AckedBy,
		&i.AckedAt,
		&i.OpenEventID,
		&i.CloseEventID,
	)
	return i, err
}

const listIncidents = `-- name: ListIncidents :many
SELECT i.id, i.monitor_id, i.project_id, i.opened_at, i.resolved_at, i.acked_by, i.acked_at, i.open_event_id, i.close_event_id, m.slug AS monitor_slug, m.name AS monitor_name, m.tags AS monitor_tags, COALESCE(e.reason, '') AS reason
FROM incidents i JOIN monitors m ON m.id = i.monitor_id LEFT JOIN events e ON e.id = i.open_event_id
WHERE i.project_id = ?1 AND (i.resolved_at IS NULL OR i.resolved_at >= ?2)
ORDER BY (i.resolved_at IS NULL) DESC, i.opened_at DESC
LIMIT ?3
`

type ListIncidentsParams struct {
	ProjectID string
	Since     *int64
	Limit     int64
}

type ListIncidentsRow struct {
	ID           string
	MonitorID    string
	ProjectID    string
	OpenedAt     int64
	ResolvedAt   *int64
	AckedBy      *string
	AckedAt      *int64
	OpenEventID  string
	CloseEventID *string
	MonitorSlug  string
	MonitorName  string
	MonitorTags  string
	Reason       string
}

func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]ListIncidentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIncidents, arg.ProjectID, arg.Since, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncidentsRow
	for rows.Next() {
		var i ListIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.ProjectID,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.AckedBy,
			&i.AckedAt,
			&i.OpenEventID,
			&i.CloseEventID,
			&i.MonitorSlug,
			&i.MonitorName,
			&i.MonitorTags,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIncidents = `-- name: ListOpenIncidents :many
SELECT i.id, i.monitor_id, i.project_id, i.opened_at, i.resolved_at, i.acked_by, i.acked_at, i.open_event_id, i.close_event_id, m.slug AS monitor_slug, m.name AS monitor_name, m.tags AS monitor_tags, COALESCE(e.reason, '') AS reason
FROM incidents i JOIN monitors m ON m.id = i.monitor_id LEFT JOIN events e ON e.id = i.open_event_id
WHERE i.project_id = ? AND i.resolved_at IS NULL
ORDER BY i.opened_at DESC
`

type ListOpenIncidentsRow struct {
	ID           string
	MonitorID    string
	ProjectID    string
	OpenedAt     int64
	ResolvedAt   *int64
	AckedBy      *string
	AckedAt      *int64
	OpenEventID  string
	CloseEventID *string
	MonitorSlug  string
	MonitorName  string
	MonitorTags  string
	Reason       string
}

func (q *Queries) ListOpenIncidents(ctx context.Context, projectID string) ([]ListOpenIncidentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenIncidents, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenIncidentsRow
	for rows.Next() {
		var i ListOpenIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.ProjectID,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.AckedBy,
			&i.AckedAt,
			&i.OpenEventID,
			&i.CloseEventID,
			&i.MonitorSlug,
			&i.MonitorName,
			&i.MonitorTags,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenUnackedIncidents = `-- name: ListOpenUnackedIncidents :many
SELECT i.id, i.monitor_id, i.project_id, i.opened_at, i.resolved_at, i.acked_by, i.acked_at, i.open_event_id, i.close_event_id, m.slug AS monitor_slug, m.name AS monitor_name
FROM incidents i JOIN monitors m ON m.id = i.monitor_id
WHERE i.resolved_at IS NULL AND i.acked_at IS NULL AND m.paused = 0
ORDER BY i.opened_at
`

type ListOpenUnackedIncidentsRow struct {
	ID           string
	MonitorID    string
	ProjectID    string
	OpenedAt     int64
	ResolvedAt   *int64
	AckedBy      *string
	AckedAt      *int64
	OpenEventID  string
	CloseEventID *string
	MonitorSlug  string
	MonitorName  string
}

// tenancy: root (dispatcher schedules repeat notifications)
func (q *Queries) ListOpenUnackedIncidents(ctx context.Context) ([]ListOpenUnackedIncidentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenUnackedIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenUnackedIncidentsRow
	for rows.Next() {
		var i ListOpenUnackedIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.ProjectID,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.AckedBy,
			&i.AckedAt,
			&i.OpenEventID,
			&i.CloseEventID,
			&i.MonitorSlug,
			&i.MonitorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openIncident = `-- name: OpenIncident :one
INSERT INTO incidents (id, monitor_id, project_id, opened_at, open_event_id)
VALUES (?, ?, ?, ?, ?)
RETURNING id, monitor_id, project_id, opened_at, resolved_at, acked_by, acked_at, open_event_id, close_event_id
`

type OpenIncidentParams struct {
	ID          string
	MonitorID   string
	ProjectID   string
	OpenedAt    int64
	OpenEventID string
}

func (q *Queries) OpenIncident(ctx context.Context, arg OpenIncidentParams) (Incident, error) {
	row := q.db.QueryRowContext(ctx, openIncident,
		arg.ID,
		arg.MonitorID,
		arg.ProjectID,
		arg.OpenedAt,
		arg.OpenEventID,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ProjectID,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.AckedBy,
		&i.AckedAt,
		&i.OpenEventID,
		&i.CloseEventID,
	)
	return i, err
}

const resolveIncident = `-- name: ResolveIncident :exec
UPDATE incidents SET resolved_at = ?, close_event_id = ?
WHERE project_id = ? AND id = ?
`

type ResolveIncidentParams struct {
	ResolvedAt   *int64
	CloseEventID *string
	ProjectID    string
	ID           string
}

func (q *Queries) ResolveIncident(ctx context.Context, arg ResolveIncidentParams) error {
	_, err := q.db.ExecContext(ctx, resolveIncident,
		arg.ResolvedAt,
		arg.CloseEventID,
		arg.ProjectID,
		arg.ID,
	)
	return err
}
