// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (id, org_id, role, note, token_hash, created_by, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, org_id, role, note, token_hash, created_by, created_at, expires_at, used_at, used_by, revoked_at
`

type CreateInviteParams struct {
	ID        string
	OrgID     string
	Role      string
	Note      string
	TokenHash string
	CreatedBy *string
	CreatedAt int64
	ExpiresAt int64
}

// tenancy: org
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, createInvite,
		arg.ID,
		arg.OrgID,
		arg.Role,
		arg.Note,
		arg.TokenHash,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Role,
		&i.Note,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
		&i.RevokedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :execrows
DELETE FROM invites WHERE org_id = ? AND id = ? AND used_at IS NULL
`

type DeleteInviteParams struct {
	OrgID string
	ID    string
}

// tenancy: org
func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInvite, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getInvite = `-- name: GetInvite :one
SELECT id, org_id, role, note, token_hash, created_by, created_at, expires_at, used_at, used_by, revoked_at FROM invites WHERE org_id = ? AND id = ?
`

type GetInviteParams struct {
	OrgID string
	ID    string
}

// tenancy: org
func (q *Queries) GetInvite(ctx context.Context, arg GetInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInvite, arg.OrgID, arg.ID)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Role,
		&i.Note,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
		&i.RevokedAt,
	)
	return i, err
}

const getInviteByHash = `-- name: GetInviteByHash :one
SELECT i.id, i.org_id, i.role, i.note, i.token_hash, i.created_by, i.created_at, i.expires_at, i.used_at, i.used_by, i.revoked_at, o.slug AS org_slug, o.name AS org_name, u.subject AS created_by_subject, u.display_name AS created_by_name
FROM invites i JOIN orgs o ON o.id = i.org_id LEFT JOIN users u ON u.id = i.created_by
WHERE i.token_hash = ?
`

type GetInviteByHashRow struct {
	ID               string
	OrgID            string
	Role             string
	Note             string
	TokenHash        string
	CreatedBy        *string
	CreatedAt        int64
	ExpiresAt        int64
	UsedAt           *int64
	UsedBy           *string
	RevokedAt        *int64
	OrgSlug          string
	OrgName          string
	CreatedBySubject *string
	CreatedByName    *string
}

// tenancy: root (the link's token establishes the org)
func (q *Queries) GetInviteByHash(ctx context.Context, tokenHash string) (GetInviteByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getInviteByHash, tokenHash)
	var i GetInviteByHashRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Role,
		&i.Note,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
		&i.RevokedAt,
		&i.OrgSlug,
		&i.OrgName,
		&i.CreatedBySubject,
		&i.CreatedByName,
	)
	return i, err
}

const listInvitesForOrg = `-- name: ListInvitesForOrg :many
SELECT i.id, i.org_id, i.role, i.note, i.token_hash, i.created_by, i.created_at, i.expires_at, i.used_at, i.used_by, i.revoked_at, u.subject AS created_by_subject, u.display_name AS created_by_name, j.subject AS used_by_subject
FROM invites i LEFT JOIN users u ON u.id = i.created_by LEFT JOIN users j ON j.id = i.used_by
WHERE i.org_id = ?
ORDER BY i.created_at DESC
`

type ListInvitesForOrgRow struct {
	ID               string
	OrgID            string
	Role             string
	Note             string
	TokenHash        string
	CreatedBy        *string
	CreatedAt        int64
	ExpiresAt        int64
	UsedAt           *int64
	UsedBy           *string
	RevokedAt        *int64
	CreatedBySubject *string
	CreatedByName    *string
	UsedBySubject    *string
}

// tenancy: org
func (q *Queries) ListInvitesForOrg(ctx context.Context, orgID string) ([]ListInvitesForOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, listInvitesForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvitesForOrgRow
	for rows.Next() {
		var i ListInvitesForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Role,
			&i.Note,
			&i.TokenHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedBy,
			&i.RevokedAt,
			&i.CreatedBySubject,
			&i.CreatedByName,
			&i.UsedBySubject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :execrows
UPDATE invites SET revoked_at = ? WHERE org_id = ? AND id = ? AND used_at IS NULL AND revoked_at IS NULL
`

type RevokeInviteParams struct {
	RevokedAt *int64
	OrgID     string
	ID        string
}

// tenancy: org
func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeInvite, arg.RevokedAt, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const useInvite = `-- name: UseInvite :execrows
UPDATE invites SET used_at = ?, used_by = ?
WHERE id = ? AND used_at IS NULL AND revoked_at IS NULL AND expires_at > ?
`

type UseInviteParams struct {
	UsedAt    *int64
	UsedBy    *string
	ID        string
	ExpiresAt int64
}

// tenancy: root (the link's token establishes the org; the row must still be open)
func (q *Queries) UseInvite(ctx context.Context, arg UseInviteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useInvite,
		arg.UsedAt,
		arg.UsedBy,
		arg.ID,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
