// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package db

import (
	"context"
)

const createMaintenance = `-- name: CreateMaintenance :one
INSERT INTO maintenance (id, project_id, name, match_tags, starts_at, ends_at, rrule, from_time, to_time, timezone, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, name, match_tags, starts_at, ends_at, rrule, from_time, to_time, timezone, created_at, updated_at, ended_until
`

type CreateMaintenanceParams struct {
	ID        string
	ProjectID string
	Name      string
	MatchTags string
	StartsAt  *int64
	EndsAt    *int64
	Rrule     *string
	FromTime  *string
	ToTime    *string
	Timezone  string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) (Maintenance, error) {
	row := q.db.QueryRowContext(ctx, createMaintenance,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.MatchTags,
		arg.StartsAt,
		arg.EndsAt,
		arg.Rrule,
		arg.FromTime,
		arg.ToTime,
		arg.Timezone,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Maintenance
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.MatchTags,
		&i.StartsAt,
		&i.EndsAt,
		&i.Rrule,
		&i.FromTime,
		&i.ToTime,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedUntil,
	)
	return i, err
}

const deleteMaintenance = `-- name: DeleteMaintenance :execrows
DELETE FROM maintenance WHERE project_id = ? AND id = ?
`

type DeleteMaintenanceParams struct {
	ProjectID string
	ID        string
}

func (q *Queries) DeleteMaintenance(ctx context.Context, arg DeleteMaintenanceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMaintenance, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMaintenance = `-- name: GetMaintenance :one
SELECT id, project_id, name, match_tags, starts_at, ends_at, rrule, from_time, to_time, timezone, created_at, updated_at, ended_until FROM maintenance WHERE project_id = ? AND id = ?
`

type GetMaintenanceParams struct {
	ProjectID string
	ID        string
}

func (q *Queries) GetMaintenance(ctx context.Context, arg GetMaintenanceParams) (Maintenance, error) {
	row := q.db.QueryRowContext(ctx, getMaintenance, arg.ProjectID, arg.ID)
	var i Maintenance
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.MatchTags,
		&i.StartsAt,
		&i.EndsAt,
		&i.Rrule,
		&i.FromTime,
		&i.ToTime,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedUntil,
	)
	return i, err
}

const listMaintenance = `-- name: ListMaintenance :many
SELECT id, project_id, name, match_tags, starts_at, ends_at, rrule, from_time, to_time, timezone, created_at, updated_at, ended_until FROM maintenance WHERE project_id = ? ORDER BY created_at, id
`

func (q *Queries) ListMaintenance(ctx context.Context, projectID string) ([]Maintenance, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenance, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Maintenance
	for rows.Next() {
		var i Maintenance
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.MatchTags,
			&i.StartsAt,
			&i.EndsAt,
			&i.Rrule,
			&i.FromTime,
			&i.ToTime,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenance = `-- name: UpdateMaintenance :one
UPDATE maintenance
SET name = ?, match_tags = ?, starts_at = ?, ends_at = ?, rrule = ?, from_time = ?, to_time = ?, timezone = ?, ended_until = ?, updated_at = ?
WHERE project_id = ? AND id = ?
RETURNING id, project_id, name, match_tags, starts_at, ends_at, rrule, from_time, to_time, timezone, created_at, updated_at, ended_until
`

type UpdateMaintenanceParams struct {
	Name       string
	MatchTags  string
	StartsAt   *int64
	EndsAt     *int64
	Rrule      *string
	FromTime   *string
	ToTime     *string
	Timezone   string
	EndedUntil *int64
	UpdatedAt  int64
	ProjectID  string
	ID         string
}

func (q *Queries) UpdateMaintenance(ctx context.Context, arg UpdateMaintenanceParams) (Maintenance, error) {
	row := q.db.QueryRowContext(ctx, updateMaintenance,
		arg.Name,
		arg.MatchTags,
		arg.StartsAt,
		arg.EndsAt,
		arg.Rrule,
		arg.FromTime,
		arg.ToTime,
		arg.Timezone,
		arg.EndedUntil,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.ID,
	)
	var i Maintenance
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.MatchTags,
		&i.StartsAt,
		&i.EndsAt,
		&i.Rrule,
		&i.FromTime,
		&i.ToTime,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndedUntil,
	)
	return i, err
}
