// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package db

import (
	"context"
)

const countOwners = `-- name: CountOwners :one
SELECT COUNT(*) FROM memberships WHERE org_id = ? AND role = 'owner'
`

// tenancy: org
func (q *Queries) CountOwners(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwners, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteHeaderMembershipsForUser = `-- name: DeleteHeaderMembershipsForUser :exec
DELETE FROM memberships WHERE user_id = ? AND source = 'header'
`

func (q *Queries) DeleteHeaderMembershipsForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteHeaderMembershipsForUser, userID)
	return err
}

const deleteMembership = `-- name: DeleteMembership :execrows
DELETE FROM memberships WHERE user_id = ? AND org_id = ?
`

type DeleteMembershipParams struct {
	UserID string
	OrgID  string
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMembership, arg.UserID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMembership = `-- name: GetMembership :one
SELECT user_id, org_id, role, source, created_at FROM memberships WHERE user_id = ? AND org_id = ?
`

type GetMembershipParams struct {
	UserID string
	OrgID  string
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, getMembership, arg.UserID, arg.OrgID)
	var i Membership
	err := row.Scan(
		&i.UserID,
		&i.OrgID,
		&i.Role,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const listMembershipsForOrg = `-- name: ListMembershipsForOrg :many
SELECT m.user_id, m.org_id, m.role, m.source, m.created_at, u.subject, u.email, u.display_name
FROM memberships m JOIN users u ON u.id = m.user_id
WHERE m.org_id = ?
ORDER BY u.subject
`

type ListMembershipsForOrgRow struct {
	UserID      string
	OrgID       string
	Role        string
	Source      string
	CreatedAt   int64
	Subject     string
	Email       string
	DisplayName string
}

func (q *Queries) ListMembershipsForOrg(ctx context.Context, orgID string) ([]ListMembershipsForOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsForOrgRow
	for rows.Next() {
		var i ListMembershipsForOrgRow
		if err := rows.Scan(
			&i.UserID,
			&i.OrgID,
			&i.Role,
			&i.Source,
			&i.CreatedAt,
			&i.Subject,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT m.user_id, m.org_id, m.role, m.source, m.created_at, o.slug AS org_slug, o.name AS org_name
FROM memberships m JOIN orgs o ON o.id = m.org_id
WHERE m.user_id = ?
ORDER BY o.slug
`

type ListMembershipsForUserRow struct {
	UserID    string
	OrgID     string
	Role      string
	Source    string
	CreatedAt int64
	OrgSlug   string
	OrgName   string
}

func (q *Queries) ListMembershipsForUser(ctx context.Context, userID string) ([]ListMembershipsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsForUserRow
	for rows.Next() {
		var i ListMembershipsForUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.OrgID,
			&i.Role,
			&i.Source,
			&i.CreatedAt,
			&i.OrgSlug,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT m.user_id, m.org_id, m.role, m.source, m.created_at, u.subject, u.email, u.display_name, u.source AS user_source, u.disabled_at,
  (SELECT MAX(s.last_seen_at) FROM sessions s WHERE s.user_id = m.user_id) AS last_seen_at
FROM memberships m JOIN users u ON u.id = m.user_id
WHERE m.org_id = ?
ORDER BY u.subject
`

type ListOrgMembersRow struct {
	UserID      string
	OrgID       string
	Role        string
	Source      string
	CreatedAt   int64
	Subject     string
	Email       string
	DisplayName string
	UserSource  string
	DisabledAt  *int64
	LastSeenAt  interface{}
}

// tenancy: org
func (q *Queries) ListOrgMembers(ctx context.Context, orgID string) ([]ListOrgMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgMembersRow
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.OrgID,
			&i.Role,
			&i.Source,
			&i.CreatedAt,
			&i.Subject,
			&i.Email,
			&i.DisplayName,
			&i.UserSource,
			&i.DisabledAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMembership = `-- name: UpsertMembership :exec
INSERT INTO memberships (user_id, org_id, role, source, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (user_id, org_id) DO UPDATE SET role = excluded.role, source = excluded.source
`

type UpsertMembershipParams struct {
	UserID    string
	OrgID     string
	Role      string
	Source    string
	CreatedAt int64
}

func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) error {
	_, err := q.db.ExecContext(ctx, upsertMembership,
		arg.UserID,
		arg.OrgID,
		arg.Role,
		arg.Source,
		arg.CreatedAt,
	)
	return err
}
