// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Agent struct {
	ID          string
	OrgID       string
	Name        string
	TokenHash   string
	LastSeenAt  *int64
	Version     *string
	Labels      string
	CreatedAt   int64
	TokenPrefix string
	LastAddr    *string
}

type ApiKey struct {
	ID         string
	ProjectID  *string
	OrgID      string
	Name       string
	Prefix     string
	Hash       string
	Access     string
	CreatedBy  *string
	CreatedAt  int64
	LastUsedAt *int64
	RevokedAt  *int64
}

type Body struct {
	ObservationID string
	ProjectID     string
	Content       []byte
	ContentType   string
	CreatedAt     int64
}

type Channel struct {
	ID        string
	ProjectID string
	OrgID     string
	Name      string
	Kind      string
	Config    string
	Enabled   bool
	CreatedAt int64
	UpdatedAt int64
}

type Delivery struct {
	ID            string
	EventID       string
	ChannelID     string
	ProjectID     string
	MonitorID     string
	RouteID       *string
	Kind          string
	Repeat        bool
	Attempt       int64
	NextAttemptAt int64
	DeliveredAt   *int64
	FailedAt      *int64
	Error         *string
	CreatedAt     int64
}

type Event struct {
	ID            string
	MonitorID     string
	ProjectID     string
	At            int64
	FromState     string
	ToState       string
	Reason        string
	ObservationID *string
}

type Incident struct {
	ID           string
	MonitorID    string
	ProjectID    string
	OpenedAt     int64
	ResolvedAt   *int64
	AckedBy      *string
	AckedAt      *int64
	OpenEventID  string
	CloseEventID *string
}

type Maintenance struct {
	ID         string
	ProjectID  string
	Name       string
	MatchTags  string
	StartsAt   *int64
	EndsAt     *int64
	Rrule      *string
	FromTime   *string
	ToTime     *string
	Timezone   string
	CreatedAt  int64
	UpdatedAt  int64
	EndedUntil *int64
}

type Membership struct {
	UserID    string
	OrgID     string
	Role      string
	Source    string
	CreatedAt int64
}

type Monitor struct {
	ID           string
	ProjectID    string
	OrgID        string
	Slug         string
	Name         string
	Kind         string
	Spec         string
	Tags         string
	State        string
	StateSince   int64
	BaseAt       int64
	LastObsAt    *int64
	LastOkAt     *int64
	NextDueAt    *int64
	Paused       bool
	FailStreak   int64
	OkStreak     int64
	RunStartedAt *int64
	RunID        *string
	AgentID      *string
	CreatedAt    int64
	UpdatedAt    int64
}

type Observation struct {
	ID         string
	MonitorID  string
	ProjectID  string
	At         int64
	Source     string
	Signal     string
	Ok         bool
	LatencyMs  *int64
	ExitCode   *int64
	RunID      *string
	DurationMs *int64
	RemoteAddr *string
	UserAgent  *string
	BodyRef    *string
	Detail     string
}

type Org struct {
	ID            string
	Slug          string
	Name          string
	QuotaMonitors *int64
	QuotaAgents   *int64
	CreatedAt     int64
}

type Project struct {
	ID               string
	OrgID            string
	Slug             string
	Name             string
	Timezone         string
	PingKey          string
	PingKeyPrev      *string
	PingKeyPrevUntil *int64
	CreatedAt        int64
}

type Route struct {
	ID           string
	ProjectID    string
	MatchTags    string
	OnStates     string
	RepeatEveryS int64
	Priority     int64
	CreatedAt    int64
	UpdatedAt    int64
}

type RouteChannel struct {
	RouteID   string
	ChannelID string
	ProjectID string
}

type SchemaMigration struct {
	Version string
}

type Session struct {
	ID            string
	UserID        string
	Csrf          string
	CreatedAt     int64
	ExpiresAt     int64
	LastProjectID *string
}

type StatusPage struct {
	ID           string
	ProjectID    string
	Slug         string
	Title        string
	MatchTags    string
	Public       bool
	PasswordHash *string
	CustomDomain *string
	CreatedAt    int64
	UpdatedAt    int64
}

type User struct {
	ID              string
	Subject         string
	Email           string
	DisplayName     string
	PasswordHash    *string
	IsInstanceAdmin bool
	CreatedAt       int64
}
