// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package db

import (
	"context"
)

const countMonitorsByState = `-- name: CountMonitorsByState :many
SELECT state, COUNT(*) AS n FROM monitors WHERE project_id = ? GROUP BY state
`

type CountMonitorsByStateRow struct {
	State string
	N     int64
}

func (q *Queries) CountMonitorsByState(ctx context.Context, projectID string) ([]CountMonitorsByStateRow, error) {
	rows, err := q.db.QueryContext(ctx, countMonitorsByState, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountMonitorsByStateRow
	for rows.Next() {
		var i CountMonitorsByStateRow
		if err := rows.Scan(&i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMonitorsInOrg = `-- name: CountMonitorsInOrg :one
SELECT COUNT(*) FROM monitors WHERE org_id = ?
`

// tenancy: org (quota check)
func (q *Queries) CountMonitorsInOrg(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMonitorsInOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (id, project_id, org_id, slug, name, kind, spec, tags, state, state_since, next_due_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, org_id, slug, name, kind, spec, tags, state, state_since, last_obs_at, last_ok_at, next_due_at, paused, fail_streak, ok_streak, run_started_at, run_id, agent_id, created_at, updated_at
`

type CreateMonitorParams struct {
	ID         string
	ProjectID  string
	OrgID      string
	Slug       string
	Name       string
	Kind       string
	Spec       string
	Tags       string
	State      string
	StateSince int64
	NextDueAt  *int64
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRowContext(ctx, createMonitor,
		arg.ID,
		arg.ProjectID,
		arg.OrgID,
		arg.Slug,
		arg.Name,
		arg.Kind,
		arg.Spec,
		arg.Tags,
		arg.State,
		arg.StateSince,
		arg.NextDueAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Spec,
		&i.Tags,
		&i.State,
		&i.StateSince,
		&i.LastObsAt,
		&i.LastOkAt,
		&i.NextDueAt,
		&i.Paused,
		&i.FailStreak,
		&i.OkStreak,
		&i.RunStartedAt,
		&i.RunID,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMonitor = `-- name: DeleteMonitor :execrows
DELETE FROM monitors WHERE project_id = ? AND id = ?
`

type DeleteMonitorParams struct {
	ProjectID string
	ID        string
}

func (q *Queries) DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMonitor, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMonitor = `-- name: GetMonitor :one
SELECT id, project_id, org_id, slug, name, kind, spec, tags, state, state_since, last_obs_at, last_ok_at, next_due_at, paused, fail_streak, ok_streak, run_started_at, run_id, agent_id, created_at, updated_at FROM monitors WHERE project_id = ? AND id = ?
`

type GetMonitorParams struct {
	ProjectID string
	ID        string
}

func (q *Queries) GetMonitor(ctx context.Context, arg GetMonitorParams) (Monitor, error) {
	row := q.db.QueryRowContext(ctx, getMonitor, arg.ProjectID, arg.ID)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Spec,
		&i.Tags,
		&i.State,
		&i.StateSince,
		&i.LastObsAt,
		&i.LastOkAt,
		&i.NextDueAt,
		&i.Paused,
		&i.FailStreak,
		&i.OkStreak,
		&i.RunStartedAt,
		&i.RunID,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMonitorByID = `-- name: GetMonitorByID :one
SELECT id, project_id, org_id, slug, name, kind, spec, tags, state, state_since, last_obs_at, last_ok_at, next_due_at, paused, fail_streak, ok_streak, run_started_at, run_id, agent_id, created_at, updated_at FROM monitors WHERE id = ?
`

// tenancy: root (scheduler reload after a bus event)
func (q *Queries) GetMonitorByID(ctx context.Context, id string) (Monitor, error) {
	row := q.db.QueryRowContext(ctx, getMonitorByID, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Spec,
		&i.Tags,
		&i.State,
		&i.StateSince,
		&i.LastObsAt,
		&i.LastOkAt,
		&i.NextDueAt,
		&i.Paused,
		&i.FailStreak,
		&i.OkStreak,
		&i.RunStartedAt,
		&i.RunID,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMonitorBySlug = `-- name: GetMonitorBySlug :one
SELECT id, project_id, org_id, slug, name, kind, spec, tags, state, state_since, last_obs_at, last_ok_at, next_due_at, paused, fail_streak, ok_streak, run_started_at, run_id, agent_id, created_at, updated_at FROM monitors WHERE project_id = ? AND slug = ?
`

type GetMonitorBySlugParams struct {
	ProjectID string
	Slug      string
}

func (q *Queries) GetMonitorBySlug(ctx context.Context, arg GetMonitorBySlugParams) (Monitor, error) {
	row := q.db.QueryRowContext(ctx, getMonitorBySlug, arg.ProjectID, arg.Slug)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Spec,
		&i.Tags,
		&i.State,
		&i.StateSince,
		&i.LastObsAt,
		&i.LastOkAt,
		&i.NextDueAt,
		&i.Paused,
		&i.FailStreak,
		&i.OkStreak,
		&i.RunStartedAt,
		&i.RunID,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueMonitors = `-- name: ListDueMonitors :many
SELECT id, project_id, org_id, slug, name, kind, spec, tags, state, state_since, last_obs_at, last_ok_at, next_due_at, paused, fail_streak, ok_streak, run_started_at, run_id, agent_id, created_at, updated_at FROM monitors
WHERE paused = 0 AND next_due_at IS NOT NULL AND next_due_at <= ?
ORDER BY next_due_at
LIMIT ?
`

type ListDueMonitorsParams struct {
	NextDueAt *int64
	Limit     int64
}

// tenancy: root (scheduler)
func (q *Queries) ListDueMonitors(ctx context.Context, arg ListDueMonitorsParams) ([]Monitor, error) {
	rows, err := q.db.QueryContext(ctx, listDueMonitors, arg.NextDueAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.Spec,
			&i.Tags,
			&i.State,
			&i.StateSince,
			&i.LastObsAt,
			&i.LastOkAt,
			&i.NextDueAt,
			&i.Paused,
			&i.FailStreak,
			&i.OkStreak,
			&i.RunStartedAt,
			&i.RunID,
			&i.AgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitors = `-- name: ListMonitors :many
SELECT id, project_id, org_id, slug, name, kind, spec, tags, state, state_since, last_obs_at, last_ok_at, next_due_at, paused, fail_streak, ok_streak, run_started_at, run_id, agent_id, created_at, updated_at FROM monitors WHERE project_id = ? ORDER BY name, id
`

func (q *Queries) ListMonitors(ctx context.Context, projectID string) ([]Monitor, error) {
	rows, err := q.db.QueryContext(ctx, listMonitors, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.Spec,
			&i.Tags,
			&i.State,
			&i.StateSince,
			&i.LastObsAt,
			&i.LastOkAt,
			&i.NextDueAt,
			&i.Paused,
			&i.FailStreak,
			&i.OkStreak,
			&i.RunStartedAt,
			&i.RunID,
			&i.AgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningMonitors = `-- name: ListRunningMonitors :many
SELECT id, project_id, org_id, slug, name, kind, spec, tags, state, state_since, last_obs_at, last_ok_at, next_due_at, paused, fail_streak, ok_streak, run_started_at, run_id, agent_id, created_at, updated_at FROM monitors WHERE paused = 0 AND run_started_at IS NOT NULL AND run_started_at <= ?
`

// tenancy: root (scheduler, max_runtime)
func (q *Queries) ListRunningMonitors(ctx context.Context, runStartedAt *int64) ([]Monitor, error) {
	rows, err := q.db.QueryContext(ctx, listRunningMonitors, runStartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.Spec,
			&i.Tags,
			&i.State,
			&i.StateSince,
			&i.LastObsAt,
			&i.LastOkAt,
			&i.NextDueAt,
			&i.Paused,
			&i.FailStreak,
			&i.OkStreak,
			&i.RunStartedAt,
			&i.RunID,
			&i.AgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDueAt = `-- name: NextDueAt :one
SELECT CAST(COALESCE(MIN(next_due_at), 0) AS INTEGER) AS next_due_at
FROM monitors WHERE paused = 0 AND next_due_at IS NOT NULL
`

// tenancy: root (scheduler)
func (q *Queries) NextDueAt(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextDueAt)
	var next_due_at int64
	err := row.Scan(&next_due_at)
	return next_due_at, err
}

const setMonitorPaused = `-- name: SetMonitorPaused :exec
UPDATE monitors
SET paused = ?, state = ?, state_since = ?, next_due_at = ?,
    fail_streak = 0, ok_streak = 0, run_started_at = NULL, run_id = NULL, updated_at = ?
WHERE project_id = ? AND id = ?
`

type SetMonitorPausedParams struct {
	Paused     bool
	State      string
	StateSince int64
	NextDueAt  *int64
	UpdatedAt  int64
	ProjectID  string
	ID         string
}

func (q *Queries) SetMonitorPaused(ctx context.Context, arg SetMonitorPausedParams) error {
	_, err := q.db.ExecContext(ctx, setMonitorPaused,
		arg.Paused,
		arg.State,
		arg.StateSince,
		arg.NextDueAt,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.ID,
	)
	return err
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors
SET name = ?, spec = ?, tags = ?, next_due_at = ?, updated_at = ?
WHERE project_id = ? AND id = ?
RETURNING id, project_id, org_id, slug, name, kind, spec, tags, state, state_since, last_obs_at, last_ok_at, next_due_at, paused, fail_streak, ok_streak, run_started_at, run_id, agent_id, created_at, updated_at
`

type UpdateMonitorParams struct {
	Name      string
	Spec      string
	Tags      string
	NextDueAt *int64
	UpdatedAt int64
	ProjectID string
	ID        string
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error) {
	row := q.db.QueryRowContext(ctx, updateMonitor,
		arg.Name,
		arg.Spec,
		arg.Tags,
		arg.NextDueAt,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.ID,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.Spec,
		&i.Tags,
		&i.State,
		&i.StateSince,
		&i.LastObsAt,
		&i.LastOkAt,
		&i.NextDueAt,
		&i.Paused,
		&i.FailStreak,
		&i.OkStreak,
		&i.RunStartedAt,
		&i.RunID,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMonitorState = `-- name: UpdateMonitorState :exec
UPDATE monitors
SET state = ?, state_since = ?, last_obs_at = ?, last_ok_at = ?, next_due_at = ?,
    fail_streak = ?, ok_streak = ?, run_started_at = ?, run_id = ?, updated_at = ?
WHERE project_id = ? AND id = ?
`

type UpdateMonitorStateParams struct {
	State        string
	StateSince   int64
	LastObsAt    *int64
	LastOkAt     *int64
	NextDueAt    *int64
	FailStreak   int64
	OkStreak     int64
	RunStartedAt *int64
	RunID        *string
	UpdatedAt    int64
	ProjectID    string
	ID           string
}

func (q *Queries) UpdateMonitorState(ctx context.Context, arg UpdateMonitorStateParams) error {
	_, err := q.db.ExecContext(ctx, updateMonitorState,
		arg.State,
		arg.StateSince,
		arg.LastObsAt,
		arg.LastOkAt,
		arg.NextDueAt,
		arg.FailStreak,
		arg.OkStreak,
		arg.RunStartedAt,
		arg.RunID,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.ID,
	)
	return err
}
