// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observations.sql

package db

import (
	"context"
)

const countObservationsAt = `-- name: CountObservationsAt :one
SELECT COUNT(*) FROM observations WHERE monitor_id = ? AND at = ? AND source = ?
`

type CountObservationsAtParams struct {
	MonitorID string
	At        int64
	Source    string
}

// tenancy: root (agent results dedupe by monitor, attempt time and source)
func (q *Queries) CountObservationsAt(ctx context.Context, arg CountObservationsAtParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countObservationsAt, arg.MonitorID, arg.At, arg.Source)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteObservationsBefore = `-- name: DeleteObservationsBefore :execrows
DELETE FROM observations WHERE at < ?
`

// tenancy: root (retention job)
func (q *Queries) DeleteObservationsBefore(ctx context.Context, at int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteObservationsBefore, at)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getObservation = `-- name: GetObservation :one
SELECT id, monitor_id, project_id, at, source, signal, ok, latency_ms, exit_code, run_id, duration_ms, remote_addr, user_agent, body_ref, detail FROM observations WHERE project_id = ? AND id = ?
`

type GetObservationParams struct {
	ProjectID string
	ID        string
}

func (q *Queries) GetObservation(ctx context.Context, arg GetObservationParams) (Observation, error) {
	row := q.db.QueryRowContext(ctx, getObservation, arg.ProjectID, arg.ID)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ProjectID,
		&i.At,
		&i.Source,
		&i.Signal,
		&i.Ok,
		&i.LatencyMs,
		&i.ExitCode,
		&i.RunID,
		&i.DurationMs,
		&i.RemoteAddr,
		&i.UserAgent,
		&i.BodyRef,
		&i.Detail,
	)
	return i, err
}

const insertObservation = `-- name: InsertObservation :exec
INSERT INTO observations (id, monitor_id, project_id, at, source, signal, ok, latency_ms, exit_code, run_id, duration_ms, remote_addr, user_agent, body_ref, detail)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertObservationParams struct {
	ID         string
	MonitorID  string
	ProjectID  string
	At         int64
	Source     string
	Signal     string
	Ok         bool
	LatencyMs  *int64
	ExitCode   *int64
	RunID      *string
	DurationMs *int64
	RemoteAddr *string
	UserAgent  *string
	BodyRef    *string
	Detail     string
}

func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) error {
	_, err := q.db.ExecContext(ctx, insertObservation,
		arg.ID,
		arg.MonitorID,
		arg.ProjectID,
		arg.At,
		arg.Source,
		arg.Signal,
		arg.Ok,
		arg.LatencyMs,
		arg.ExitCode,
		arg.RunID,
		arg.DurationMs,
		arg.RemoteAddr,
		arg.UserAgent,
		arg.BodyRef,
		arg.Detail,
	)
	return err
}

const lastObservation = `-- name: LastObservation :one
SELECT id, monitor_id, project_id, at, source, signal, ok, latency_ms, exit_code, run_id, duration_ms, remote_addr, user_agent, body_ref, detail FROM observations
WHERE project_id = ? AND monitor_id = ?
ORDER BY at DESC, id DESC
LIMIT 1
`

type LastObservationParams struct {
	ProjectID string
	MonitorID string
}

func (q *Queries) LastObservation(ctx context.Context, arg LastObservationParams) (Observation, error) {
	row := q.db.QueryRowContext(ctx, lastObservation, arg.ProjectID, arg.MonitorID)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ProjectID,
		&i.At,
		&i.Source,
		&i.Signal,
		&i.Ok,
		&i.LatencyMs,
		&i.ExitCode,
		&i.RunID,
		&i.DurationMs,
		&i.RemoteAddr,
		&i.UserAgent,
		&i.BodyRef,
		&i.Detail,
	)
	return i, err
}

const listLatenciesSince = `-- name: ListLatenciesSince :many
SELECT monitor_id, at, latency_ms FROM observations
WHERE project_id = ? AND at >= ? AND latency_ms IS NOT NULL
ORDER BY at
`

type ListLatenciesSinceParams struct {
	ProjectID string
	At        int64
}

type ListLatenciesSinceRow struct {
	MonitorID string
	At        int64
	LatencyMs *int64
}

func (q *Queries) ListLatenciesSince(ctx context.Context, arg ListLatenciesSinceParams) ([]ListLatenciesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatenciesSince, arg.ProjectID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatenciesSinceRow
	for rows.Next() {
		var i ListLatenciesSinceRow
		if err := rows.Scan(&i.MonitorID, &i.At, &i.LatencyMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservations = `-- name: ListObservations :many
SELECT id, monitor_id, project_id, at, source, signal, ok, latency_ms, exit_code, run_id, duration_ms, remote_addr, user_agent, body_ref, detail FROM observations
WHERE project_id = ?1 AND monitor_id = ?2
  AND at >= ?3 AND at <= ?4
  AND (at < ?5 OR (at = ?5 AND id < ?6))
  AND (?7 = ''
    OR (?7 = 'ok' AND ok = 1 AND signal IN ('ok', 'exit'))
    OR (?7 = 'fail' AND ok = 0 AND signal NOT IN ('start', 'log'))
    OR (?7 = 'run' AND signal IN ('start', 'log')))
ORDER BY at DESC, id DESC
LIMIT ?8
`

type ListObservationsParams struct {
	ProjectID string
	MonitorID string
	Since     int64
	Until     int64
	CursorAt  int64
	CursorID  string
	Kind      interface{}
	PageSize  int64
}

// kind narrows the page: ” for all, 'ok' for successful pings and checks,
// 'fail' for failures (fail pings, non-zero exits, run timeouts, failed and
// confirming checks), 'run' for start and log signals.
func (q *Queries) ListObservations(ctx context.Context, arg ListObservationsParams) ([]Observation, error) {
	rows, err := q.db.QueryContext(ctx, listObservations,
		arg.ProjectID,
		arg.MonitorID,
		arg.Since,
		arg.Until,
		arg.CursorAt,
		arg.CursorID,
		arg.Kind,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Observation
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.ProjectID,
			&i.At,
			&i.Source,
			&i.Signal,
			&i.Ok,
			&i.LatencyMs,
			&i.ExitCode,
			&i.RunID,
			&i.DurationMs,
			&i.RemoteAddr,
			&i.UserAgent,
			&i.BodyRef,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsSince = `-- name: ListObservationsSince :many
SELECT id, monitor_id, project_id, at, source, signal, ok, latency_ms, exit_code, run_id, duration_ms, remote_addr, user_agent, body_ref, detail FROM observations
WHERE project_id = ? AND monitor_id = ? AND at >= ?
ORDER BY at, id
`

type ListObservationsSinceParams struct {
	ProjectID string
	MonitorID string
	At        int64
}

func (q *Queries) ListObservationsSince(ctx context.Context, arg ListObservationsSinceParams) ([]Observation, error) {
	rows, err := q.db.QueryContext(ctx, listObservationsSince, arg.ProjectID, arg.MonitorID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Observation
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.ProjectID,
			&i.At,
			&i.Source,
			&i.Signal,
			&i.Ok,
			&i.LatencyMs,
			&i.ExitCode,
			&i.RunID,
			&i.DurationMs,
			&i.RemoteAddr,
			&i.UserAgent,
			&i.BodyRef,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
