// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org_routes.sql

package db

import (
	"context"
)

const countOrgRoutesForChannel = `-- name: CountOrgRoutesForChannel :one
SELECT COUNT(*) FROM org_route_channels WHERE org_id = ? AND channel_id = ?
`

type CountOrgRoutesForChannelParams struct {
	OrgID     string
	ChannelID string
}

func (q *Queries) CountOrgRoutesForChannel(ctx context.Context, arg CountOrgRoutesForChannelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrgRoutesForChannel, arg.OrgID, arg.ChannelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrgRoute = `-- name: CreateOrgRoute :one
INSERT INTO org_routes (id, org_id, projects, match_tags, on_states, repeat_every_s, priority, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, org_id, projects, match_tags, on_states, repeat_every_s, priority, created_at, updated_at
`

type CreateOrgRouteParams struct {
	ID           string
	OrgID        string
	Projects     string
	MatchTags    string
	OnStates     string
	RepeatEveryS int64
	Priority     int64
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) CreateOrgRoute(ctx context.Context, arg CreateOrgRouteParams) (OrgRoute, error) {
	row := q.db.QueryRowContext(ctx, createOrgRoute,
		arg.ID,
		arg.OrgID,
		arg.Projects,
		arg.MatchTags,
		arg.OnStates,
		arg.RepeatEveryS,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i OrgRoute
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Projects,
		&i.MatchTags,
		&i.OnStates,
		&i.RepeatEveryS,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrgRoute = `-- name: DeleteOrgRoute :execrows
DELETE FROM org_routes WHERE org_id = ? AND id = ?
`

type DeleteOrgRouteParams struct {
	OrgID string
	ID    string
}

func (q *Queries) DeleteOrgRoute(ctx context.Context, arg DeleteOrgRouteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrgRoute, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOrgRouteChannels = `-- name: DeleteOrgRouteChannels :exec
DELETE FROM org_route_channels WHERE org_id = ? AND route_id = ?
`

type DeleteOrgRouteChannelsParams struct {
	OrgID   string
	RouteID string
}

func (q *Queries) DeleteOrgRouteChannels(ctx context.Context, arg DeleteOrgRouteChannelsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOrgRouteChannels, arg.OrgID, arg.RouteID)
	return err
}

const deleteOrphanOrgRoutes = `-- name: DeleteOrphanOrgRoutes :execrows
DELETE FROM org_routes WHERE org_routes.org_id = ? AND NOT EXISTS (SELECT 1 FROM org_route_channels rc WHERE rc.route_id = org_routes.id)
`

func (q *Queries) DeleteOrphanOrgRoutes(ctx context.Context, orgID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrphanOrgRoutes, orgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOrgRoute = `-- name: GetOrgRoute :one
SELECT id, org_id, projects, match_tags, on_states, repeat_every_s, priority, created_at, updated_at FROM org_routes WHERE org_id = ? AND id = ?
`

type GetOrgRouteParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetOrgRoute(ctx context.Context, arg GetOrgRouteParams) (OrgRoute, error) {
	row := q.db.QueryRowContext(ctx, getOrgRoute, arg.OrgID, arg.ID)
	var i OrgRoute
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Projects,
		&i.MatchTags,
		&i.OnStates,
		&i.RepeatEveryS,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrgRouteChannel = `-- name: InsertOrgRouteChannel :exec
INSERT INTO org_route_channels (route_id, channel_id, org_id) VALUES (?, ?, ?)
`

type InsertOrgRouteChannelParams struct {
	RouteID   string
	ChannelID string
	OrgID     string
}

func (q *Queries) InsertOrgRouteChannel(ctx context.Context, arg InsertOrgRouteChannelParams) error {
	_, err := q.db.ExecContext(ctx, insertOrgRouteChannel, arg.RouteID, arg.ChannelID, arg.OrgID)
	return err
}

const listOrgRouteChannels = `-- name: ListOrgRouteChannels :many
SELECT rc.route_id, c.id AS channel_id, c.name AS channel_name, c.kind AS channel_kind, c.enabled AS channel_enabled
FROM org_route_channels rc JOIN channels c ON c.id = rc.channel_id
WHERE rc.org_id = ?
ORDER BY rc.route_id, c.name
`

type ListOrgRouteChannelsRow struct {
	RouteID        string
	ChannelID      string
	ChannelName    string
	ChannelKind    string
	ChannelEnabled bool
}

// tenancy: org (org channels, project_id NULL)
func (q *Queries) ListOrgRouteChannels(ctx context.Context, orgID string) ([]ListOrgRouteChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgRouteChannels, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgRouteChannelsRow
	for rows.Next() {
		var i ListOrgRouteChannelsRow
		if err := rows.Scan(
			&i.RouteID,
			&i.ChannelID,
			&i.ChannelName,
			&i.ChannelKind,
			&i.ChannelEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgRoutes = `-- name: ListOrgRoutes :many
SELECT id, org_id, projects, match_tags, on_states, repeat_every_s, priority, created_at, updated_at FROM org_routes WHERE org_id = ? ORDER BY priority DESC, created_at, id
`

func (q *Queries) ListOrgRoutes(ctx context.Context, orgID string) ([]OrgRoute, error) {
	rows, err := q.db.QueryContext(ctx, listOrgRoutes, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgRoute
	for rows.Next() {
		var i OrgRoute
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Projects,
			&i.MatchTags,
			&i.OnStates,
			&i.RepeatEveryS,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrgRoute = `-- name: UpdateOrgRoute :one
UPDATE org_routes
SET projects = ?, match_tags = ?, on_states = ?, repeat_every_s = ?, priority = ?, updated_at = ?
WHERE org_id = ? AND id = ?
RETURNING id, org_id, projects, match_tags, on_states, repeat_every_s, priority, created_at, updated_at
`

type UpdateOrgRouteParams struct {
	Projects     string
	MatchTags    string
	OnStates     string
	RepeatEveryS int64
	Priority     int64
	UpdatedAt    int64
	OrgID        string
	ID           string
}

func (q *Queries) UpdateOrgRoute(ctx context.Context, arg UpdateOrgRouteParams) (OrgRoute, error) {
	row := q.db.QueryRowContext(ctx, updateOrgRoute,
		arg.Projects,
		arg.MatchTags,
		arg.OnStates,
		arg.RepeatEveryS,
		arg.Priority,
		arg.UpdatedAt,
		arg.OrgID,
		arg.ID,
	)
	var i OrgRoute
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Projects,
		&i.MatchTags,
		&i.OnStates,
		&i.RepeatEveryS,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
