// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package db

import (
	"context"
)

const countOrgs = `-- name: CountOrgs :one
SELECT COUNT(*) FROM orgs
`

func (q *Queries) CountOrgs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrgs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (id, slug, name, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, slug, name, quota_monitors, quota_agents, created_at
`

type CreateOrgParams struct {
	ID        string
	Slug      string
	Name      string
	CreatedAt int64
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRowContext(ctx, createOrg,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.CreatedAt,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.QuotaMonitors,
		&i.QuotaAgents,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrg = `-- name: DeleteOrg :execrows
DELETE FROM orgs WHERE id = ?
`

func (q *Queries) DeleteOrg(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrg, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOrg = `-- name: GetOrg :one
SELECT id, slug, name, quota_monitors, quota_agents, created_at FROM orgs WHERE id = ?
`

func (q *Queries) GetOrg(ctx context.Context, id string) (Org, error) {
	row := q.db.QueryRowContext(ctx, getOrg, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.QuotaMonitors,
		&i.QuotaAgents,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT id, slug, name, quota_monitors, quota_agents, created_at FROM orgs WHERE slug = ?
`

func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (Org, error) {
	row := q.db.QueryRowContext(ctx, getOrgBySlug, slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.QuotaMonitors,
		&i.QuotaAgents,
		&i.CreatedAt,
	)
	return i, err
}

const listOrgs = `-- name: ListOrgs :many
SELECT id, slug, name, quota_monitors, quota_agents, created_at FROM orgs ORDER BY slug
`

func (q *Queries) ListOrgs(ctx context.Context) ([]Org, error) {
	rows, err := q.db.QueryContext(ctx, listOrgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.QuotaMonitors,
			&i.QuotaAgents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrgQuotas = `-- name: SetOrgQuotas :exec
UPDATE orgs SET quota_monitors = ?, quota_agents = ? WHERE id = ?
`

type SetOrgQuotasParams struct {
	QuotaMonitors *int64
	QuotaAgents   *int64
	ID            string
}

func (q *Queries) SetOrgQuotas(ctx context.Context, arg SetOrgQuotasParams) error {
	_, err := q.db.ExecContext(ctx, setOrgQuotas, arg.QuotaMonitors, arg.QuotaAgents, arg.ID)
	return err
}

const updateOrgName = `-- name: UpdateOrgName :exec
UPDATE orgs SET name = ? WHERE id = ?
`

type UpdateOrgNameParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateOrgName(ctx context.Context, arg UpdateOrgNameParams) error {
	_, err := q.db.ExecContext(ctx, updateOrgName, arg.Name, arg.ID)
	return err
}
