// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects WHERE org_id = ?
`

func (q *Queries) CountProjects(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjects, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, org_id, slug, name, timezone, ping_key, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, org_id, slug, name, timezone, ping_key, ping_key_prev, ping_key_prev_until, created_at
`

type CreateProjectParams struct {
	ID        string
	OrgID     string
	Slug      string
	Name      string
	Timezone  string
	PingKey   string
	CreatedAt int64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.OrgID,
		arg.Slug,
		arg.Name,
		arg.Timezone,
		arg.PingKey,
		arg.CreatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Timezone,
		&i.PingKey,
		&i.PingKeyPrev,
		&i.PingKeyPrevUntil,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE org_id = ? AND id = ?
`

type DeleteProjectParams struct {
	OrgID string
	ID    string
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProject, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProject = `-- name: GetProject :one
SELECT id, org_id, slug, name, timezone, ping_key, ping_key_prev, ping_key_prev_until, created_at FROM projects WHERE org_id = ? AND id = ?
`

type GetProjectParams struct {
	OrgID string
	ID    string
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, arg.OrgID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Timezone,
		&i.PingKey,
		&i.PingKeyPrev,
		&i.PingKeyPrevUntil,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, org_id, slug, name, timezone, ping_key, ping_key_prev, ping_key_prev_until, created_at FROM projects WHERE id = ?
`

// tenancy: root (auth establishes the scope from an API key's project id)
func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Timezone,
		&i.PingKey,
		&i.PingKeyPrev,
		&i.PingKeyPrevUntil,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByPingKey = `-- name: GetProjectByPingKey :one
SELECT id, org_id, slug, name, timezone, ping_key, ping_key_prev, ping_key_prev_until, created_at FROM projects
WHERE ping_key = ?1 OR (ping_key_prev = ?1 AND ping_key_prev_until > ?2)
`

type GetProjectByPingKeyParams struct {
	Key string
	Now *int64
}

// tenancy: root (ping ingress resolves the project from the key)
func (q *Queries) GetProjectByPingKey(ctx context.Context, arg GetProjectByPingKeyParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByPingKey, arg.Key, arg.Now)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Timezone,
		&i.PingKey,
		&i.PingKeyPrev,
		&i.PingKeyPrevUntil,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, org_id, slug, name, timezone, ping_key, ping_key_prev, ping_key_prev_until, created_at FROM projects WHERE org_id = ? AND slug = ?
`

type GetProjectBySlugParams struct {
	OrgID string
	Slug  string
}

func (q *Queries) GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectBySlug, arg.OrgID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Timezone,
		&i.PingKey,
		&i.PingKeyPrev,
		&i.PingKeyPrevUntil,
		&i.CreatedAt,
	)
	return i, err
}

const listAllProjects = `-- name: ListAllProjects :many
SELECT p.id, p.org_id, p.slug, p.name, p.timezone, p.ping_key, p.ping_key_prev, p.ping_key_prev_until, p.created_at, o.slug AS org_slug, o.name AS org_name
FROM projects p JOIN orgs o ON o.id = p.org_id
ORDER BY o.slug, p.slug
`

type ListAllProjectsRow struct {
	Project Project
	OrgSlug string
	OrgName string
}

// tenancy: root (instance admin)
func (q *Queries) ListAllProjects(ctx context.Context) ([]ListAllProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllProjectsRow
	for rows.Next() {
		var i ListAllProjectsRow
		if err := rows.Scan(
			&i.Project.ID,
			&i.Project.OrgID,
			&i.Project.Slug,
			&i.Project.Name,
			&i.Project.Timezone,
			&i.Project.PingKey,
			&i.Project.PingKeyPrev,
			&i.Project.PingKeyPrevUntil,
			&i.Project.CreatedAt,
			&i.OrgSlug,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, org_id, slug, name, timezone, ping_key, ping_key_prev, ping_key_prev_until, created_at FROM projects WHERE org_id = ? ORDER BY slug
`

func (q *Queries) ListProjects(ctx context.Context, orgID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.Timezone,
			&i.PingKey,
			&i.PingKeyPrev,
			&i.PingKeyPrevUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.org_id, p.slug, p.name, p.timezone, p.ping_key, p.ping_key_prev, p.ping_key_prev_until, p.created_at, o.slug AS org_slug, o.name AS org_name, m.role
FROM projects p
JOIN orgs o ON o.id = p.org_id
JOIN memberships m ON m.org_id = p.org_id
WHERE m.user_id = ?
ORDER BY o.slug, p.slug
`

type ListProjectsForUserRow struct {
	Project Project
	OrgSlug string
	OrgName string
	Role    string
}

// tenancy: root (the user's memberships are the scope)
func (q *Queries) ListProjectsForUser(ctx context.Context, userID string) ([]ListProjectsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsForUserRow
	for rows.Next() {
		var i ListProjectsForUserRow
		if err := rows.Scan(
			&i.Project.ID,
			&i.Project.OrgID,
			&i.Project.Slug,
			&i.Project.Name,
			&i.Project.Timezone,
			&i.Project.PingKey,
			&i.Project.PingKeyPrev,
			&i.Project.PingKeyPrevUntil,
			&i.Project.CreatedAt,
			&i.OrgSlug,
			&i.OrgName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotatePingKey = `-- name: RotatePingKey :exec
UPDATE projects
SET ping_key = ?, ping_key_prev = ping_key, ping_key_prev_until = ?
WHERE org_id = ? AND id = ?
`

type RotatePingKeyParams struct {
	PingKey          string
	PingKeyPrevUntil *int64
	OrgID            string
	ID               string
}

func (q *Queries) RotatePingKey(ctx context.Context, arg RotatePingKeyParams) error {
	_, err := q.db.ExecContext(ctx, rotatePingKey,
		arg.PingKey,
		arg.PingKeyPrevUntil,
		arg.OrgID,
		arg.ID,
	)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects SET name = ?, timezone = ? WHERE org_id = ? AND id = ?
`

type UpdateProjectParams struct {
	Name     string
	Timezone string
	OrgID    string
	ID       string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.Timezone,
		arg.OrgID,
		arg.ID,
	)
	return err
}
