// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AckIncident(ctx context.Context, arg AckIncidentParams) (int64, error)
	BumpLoginChallenge(ctx context.Context, id string) (int64, error)
	// tenancy: root (agent gateway)
	ClearAgentMonitors(ctx context.Context, agentID *string) (int64, error)
	// tenancy: org
	CountAgents(ctx context.Context, orgID string) (int64, error)
	// tenancy: root (the service scopes by org_id and project_id)
	CountAudit(ctx context.Context, arg CountAuditParams) (CountAuditRow, error)
	// tenancy: root (dispatcher keeps per-monitor order)
	CountEarlierPendingDeliveries(ctx context.Context, arg CountEarlierPendingDeliveriesParams) (int64, error)
	CountMonitorsByState(ctx context.Context, projectID string) ([]CountMonitorsByStateRow, error)
	// tenancy: org (quota check)
	CountMonitorsInOrg(ctx context.Context, orgID string) (int64, error)
	// tenancy: root (agent results dedupe by monitor, attempt time and source)
	CountObservationsAt(ctx context.Context, arg CountObservationsAtParams) (int64, error)
	CountOpenIncidents(ctx context.Context, projectID string) (int64, error)
	// tenancy: root (metrics endpoint, instance-wide)
	CountOpenIncidentsByProject(ctx context.Context) ([]CountOpenIncidentsByProjectRow, error)
	CountOrgs(ctx context.Context) (int64, error)
	// tenancy: org
	CountOwners(ctx context.Context, orgID string) (int64, error)
	// tenancy: root (metrics endpoint)
	CountPendingDeliveries(ctx context.Context) (int64, error)
	CountProjects(ctx context.Context, orgID string) (int64, error)
	CountRecoveryCodes(ctx context.Context, userID string) (CountRecoveryCodesRow, error)
	CountRoutesForChannel(ctx context.Context, arg CountRoutesForChannelParams) (int64, error)
	// tenancy: root (the service scopes by org_id and project_id)
	CountStateEvents(ctx context.Context, arg CountStateEventsParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	// tenancy: org
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	// tenancy: org
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	CreateLoginChallenge(ctx context.Context, arg CreateLoginChallengeParams) error
	CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) (Maintenance, error)
	CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error)
	CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// tenancy: root (instance admin)
	CreateResetToken(ctx context.Context, arg CreateResetTokenParams) error
	CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateStatusPage(ctx context.Context, arg CreateStatusPageParams) (StatusPage, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// tenancy: org
	DeleteAgent(ctx context.Context, arg DeleteAgentParams) (int64, error)
	// tenancy: root (retention job)
	DeleteBodiesBefore(ctx context.Context, createdAt int64) (int64, error)
	DeleteChannel(ctx context.Context, arg DeleteChannelParams) (int64, error)
	DeleteExpiredLoginChallenges(ctx context.Context, expiresAt int64) (int64, error)
	DeleteExpiredSessions(ctx context.Context, expiresAt int64) (int64, error)
	DeleteHeaderMembershipsForUser(ctx context.Context, userID string) error
	// tenancy: org
	DeleteInvite(ctx context.Context, arg DeleteInviteParams) (int64, error)
	DeleteLoginChallenge(ctx context.Context, id string) error
	DeleteMaintenance(ctx context.Context, arg DeleteMaintenanceParams) (int64, error)
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error)
	DeleteMembershipsBySource(ctx context.Context, arg DeleteMembershipsBySourceParams) error
	DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) (int64, error)
	// tenancy: root (retention job)
	DeleteObservationsBefore(ctx context.Context, at int64) (int64, error)
	DeleteOrg(ctx context.Context, id string) (int64, error)
	DeleteOrphanRoutes(ctx context.Context, projectID string) (int64, error)
	DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) (int64, error)
	DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error)
	// tenancy: root (follows the user)
	DeleteRecoveryCodes(ctx context.Context, userID string) error
	DeleteRoute(ctx context.Context, arg DeleteRouteParams) (int64, error)
	DeleteRouteChannels(ctx context.Context, arg DeleteRouteChannelsParams) error
	DeleteSession(ctx context.Context, id string) error
	DeleteStatusPage(ctx context.Context, arg DeleteStatusPageParams) (int64, error)
	DeleteUserSessions(ctx context.Context, userID string) error
	EnableUserTOTP(ctx context.Context, arg EnableUserTOTPParams) error
	GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error)
	// tenancy: org
	GetAgent(ctx context.Context, arg GetAgentParams) (Agent, error)
	// tenancy: org
	GetAgentByName(ctx context.Context, arg GetAgentByNameParams) (Agent, error)
	GetBody(ctx context.Context, arg GetBodyParams) (Body, error)
	GetChannel(ctx context.Context, arg GetChannelParams) (Channel, error)
	GetChannelByName(ctx context.Context, arg GetChannelByNameParams) (Channel, error)
	GetEvent(ctx context.Context, arg GetEventParams) (Event, error)
	GetIncident(ctx context.Context, arg GetIncidentParams) (GetIncidentRow, error)
	// tenancy: root (instance facts)
	GetInstanceMeta(ctx context.Context, name string) (InstanceMetum, error)
	// tenancy: org
	GetInvite(ctx context.Context, arg GetInviteParams) (Invite, error)
	// tenancy: root (the link's token establishes the org)
	GetInviteByHash(ctx context.Context, tokenHash string) (GetInviteByHashRow, error)
	GetLoginChallenge(ctx context.Context, arg GetLoginChallengeParams) (LoginChallenge, error)
	GetMaintenance(ctx context.Context, arg GetMaintenanceParams) (Maintenance, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetMonitor(ctx context.Context, arg GetMonitorParams) (Monitor, error)
	// tenancy: root (scheduler reload after a bus event)
	GetMonitorByID(ctx context.Context, id string) (Monitor, error)
	GetMonitorBySlug(ctx context.Context, arg GetMonitorBySlugParams) (Monitor, error)
	GetObservation(ctx context.Context, arg GetObservationParams) (Observation, error)
	GetOpenIncidentForMonitor(ctx context.Context, arg GetOpenIncidentForMonitorParams) (Incident, error)
	GetOrg(ctx context.Context, id string) (Org, error)
	GetOrgBySlug(ctx context.Context, slug string) (Org, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	// tenancy: root (auth establishes the scope from an API key's project id)
	GetProjectByID(ctx context.Context, id string) (Project, error)
	// tenancy: root (ping ingress resolves the project from the key)
	GetProjectByPingKey(ctx context.Context, arg GetProjectByPingKeyParams) (Project, error)
	GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error)
	// tenancy: root (the link's token establishes the user)
	GetResetTokenByHash(ctx context.Context, tokenHash string) (GetResetTokenByHashRow, error)
	GetRoute(ctx context.Context, arg GetRouteParams) (Route, error)
	GetSession(ctx context.Context, arg GetSessionParams) (Session, error)
	GetStatusPage(ctx context.Context, arg GetStatusPageParams) (StatusPage, error)
	// tenancy: root (public page served on its custom domain)
	GetStatusPageByDomain(ctx context.Context, customDomain *string) (StatusPage, error)
	// tenancy: root (public page: the slug is unique per instance)
	GetStatusPageBySlug(ctx context.Context, slug string) (StatusPage, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserBySubject(ctx context.Context, subject string) (User, error)
	// tenancy: root (written inside the transaction of the action, for its scope)
	InsertAudit(ctx context.Context, arg InsertAuditParams) error
	InsertBody(ctx context.Context, arg InsertBodyParams) error
	InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertObservation(ctx context.Context, arg InsertObservationParams) error
	InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error
	InsertRouteChannel(ctx context.Context, arg InsertRouteChannelParams) error
	// tenancy: root (dispatcher, repeat_every)
	LastDeliveryForRoute(ctx context.Context, arg LastDeliveryForRouteParams) (Delivery, error)
	LastObservation(ctx context.Context, arg LastObservationParams) (Observation, error)
	LastSentForChannel(ctx context.Context, arg LastSentForChannelParams) (int64, error)
	ListAPIKeys(ctx context.Context, projectID *string) ([]ApiKey, error)
	// tenancy: root (bearer lookup establishes the scope)
	ListAPIKeysByPrefix(ctx context.Context, prefix string) ([]ApiKey, error)
	// tenancy: root (agent gateway, for a verified agent)
	ListAgentMonitors(ctx context.Context, agentID *string) ([]Monitor, error)
	// tenancy: org
	ListAgents(ctx context.Context, orgID string) ([]Agent, error)
	// tenancy: root (bearer lookup establishes the org)
	ListAgentsByPrefix(ctx context.Context, tokenPrefix string) ([]Agent, error)
	// tenancy: root (offline sweep, instance-wide)
	ListAgentsSeenBefore(ctx context.Context, lastSeenAt *int64) ([]Agent, error)
	// tenancy: root (instance admin: every user's roles)
	ListAllMemberships(ctx context.Context) ([]ListAllMembershipsRow, error)
	// tenancy: root (instance admin)
	ListAllProjects(ctx context.Context) ([]ListAllProjectsRow, error)
	// tenancy: root (the service scopes by org_id and project_id below)
	// The log: admin actions from audit and state flips from events, newest
	// first, 51 rows so the caller knows whether an older page exists. Account
	// rows (sign-ins, two-factor, passwords) carry no org; an org's log shows
	// those of its members.
	ListAudit(ctx context.Context, arg ListAuditParams) ([]ListAuditRow, error)
	// tenancy: root (the service scopes by org_id and project_id)
	ListAuditActors(ctx context.Context, arg ListAuditActorsParams) ([]string, error)
	ListChannels(ctx context.Context, projectID string) ([]Channel, error)
	ListDeliveriesForEvent(ctx context.Context, arg ListDeliveriesForEventParams) ([]Delivery, error)
	// tenancy: root (checker pool; remote checks belong to an agent)
	ListDueChecks(ctx context.Context, arg ListDueChecksParams) ([]string, error)
	// tenancy: root (dispatcher)
	ListDueDeliveries(ctx context.Context, arg ListDueDeliveriesParams) ([]Delivery, error)
	// tenancy: root (scheduler)
	ListDueMonitors(ctx context.Context, arg ListDueMonitorsParams) ([]Monitor, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListEventsPage(ctx context.Context, arg ListEventsPageParams) ([]Event, error)
	ListEventsSince(ctx context.Context, arg ListEventsSinceParams) ([]Event, error)
	ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]ListIncidentsRow, error)
	// tenancy: org
	ListInvitesForOrg(ctx context.Context, orgID string) ([]ListInvitesForOrgRow, error)
	ListLatenciesSince(ctx context.Context, arg ListLatenciesSinceParams) ([]ListLatenciesSinceRow, error)
	ListMaintenance(ctx context.Context, projectID string) ([]Maintenance, error)
	ListMembershipsForOrg(ctx context.Context, orgID string) ([]ListMembershipsForOrgRow, error)
	ListMembershipsForUser(ctx context.Context, userID string) ([]ListMembershipsForUserRow, error)
	ListMonitors(ctx context.Context, projectID string) ([]Monitor, error)
	// tenancy: root (metrics endpoint, instance-wide)
	ListMonitorsForMetrics(ctx context.Context) ([]ListMonitorsForMetricsRow, error)
	// kind narrows the page: '' for all, 'ok' for successful pings and checks,
	// 'fail' for failures (fail pings, non-zero exits, run timeouts, failed and
	// confirming checks), 'run' for start and log signals.
	ListObservations(ctx context.Context, arg ListObservationsParams) ([]Observation, error)
	ListObservationsSince(ctx context.Context, arg ListObservationsSinceParams) ([]Observation, error)
	ListOpenIncidents(ctx context.Context, projectID string) ([]ListOpenIncidentsRow, error)
	// tenancy: root (dispatcher schedules repeat notifications)
	ListOpenUnackedIncidents(ctx context.Context) ([]ListOpenUnackedIncidentsRow, error)
	// tenancy: org (org keys have no project)
	ListOrgAPIKeys(ctx context.Context, orgID string) ([]ApiKey, error)
	// tenancy: org
	ListOrgMembers(ctx context.Context, orgID string) ([]ListOrgMembersRow, error)
	ListOrgs(ctx context.Context) ([]Org, error)
	ListProjectEvents(ctx context.Context, arg ListProjectEventsParams) ([]ListProjectEventsRow, error)
	ListProjectEventsSince(ctx context.Context, arg ListProjectEventsSinceParams) ([]Event, error)
	ListProjects(ctx context.Context, orgID string) ([]Project, error)
	// tenancy: root (the user's memberships are the scope)
	ListProjectsForUser(ctx context.Context, userID string) ([]ListProjectsForUserRow, error)
	ListRecentDeliveries(ctx context.Context, arg ListRecentDeliveriesParams) ([]ListRecentDeliveriesRow, error)
	ListRecoveryCodes(ctx context.Context, userID string) ([]ListRecoveryCodesRow, error)
	// tenancy: root (agent gateway assigns per org)
	ListRemoteMonitors(ctx context.Context, orgID string) ([]Monitor, error)
	ListRouteChannels(ctx context.Context, projectID string) ([]ListRouteChannelsRow, error)
	ListRoutes(ctx context.Context, projectID string) ([]Route, error)
	// tenancy: root (scheduler, max_runtime)
	ListRunningMonitors(ctx context.Context, runStartedAt *int64) ([]Monitor, error)
	ListStatusPages(ctx context.Context, projectID string) ([]StatusPage, error)
	// tenancy: root (offline sweep)
	ListUnassignedRemoteMonitors(ctx context.Context, updatedAt int64) ([]Monitor, error)
	ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]Session, error)
	ListUsers(ctx context.Context) ([]User, error)
	// tenancy: root (instance admin)
	ListUsersWithSeen(ctx context.Context) ([]ListUsersWithSeenRow, error)
	// tenancy: root (dispatcher)
	MarkDeliveryDelivered(ctx context.Context, arg MarkDeliveryDeliveredParams) error
	// tenancy: root (dispatcher)
	MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error
	// tenancy: root (checker pool)
	NextCheckDueAt(ctx context.Context) (int64, error)
	// tenancy: root (scheduler)
	NextDueAt(ctx context.Context) (int64, error)
	OpenIncident(ctx context.Context, arg OpenIncidentParams) (Incident, error)
	// tenancy: root (dispatcher)
	RescheduleDelivery(ctx context.Context, arg RescheduleDeliveryParams) error
	// tenancy: root (instance admin, or the account itself)
	ResetUserTOTP(ctx context.Context, id string) error
	ResolveIncident(ctx context.Context, arg ResolveIncidentParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	// tenancy: org
	RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error)
	// tenancy: org (org keys have no project)
	RevokeOrgAPIKey(ctx context.Context, arg RevokeOrgAPIKeyParams) (int64, error)
	RotatePingKey(ctx context.Context, arg RotatePingKeyParams) error
	SetChannelEnabled(ctx context.Context, arg SetChannelEnabledParams) (Channel, error)
	SetInstanceAdmin(ctx context.Context, arg SetInstanceAdminParams) (int64, error)
	// tenancy: root (instance facts)
	SetInstanceMeta(ctx context.Context, arg SetInstanceMetaParams) error
	// tenancy: root (agent gateway)
	SetMonitorAgent(ctx context.Context, arg SetMonitorAgentParams) error
	SetMonitorPaused(ctx context.Context, arg SetMonitorPausedParams) error
	SetOrgQuotas(ctx context.Context, arg SetOrgQuotasParams) error
	SetSessionProject(ctx context.Context, arg SetSessionProjectParams) error
	// tenancy: root (instance admin)
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SetUserSource(ctx context.Context, arg SetUserSourceParams) error
	SetUserTOTPLastStep(ctx context.Context, arg SetUserTOTPLastStepParams) error
	// Account: two-factor secrets, recovery codes, sign-in challenges and a
	// person's own sessions. All keyed by user, never by org.
	SetUserTOTPSecret(ctx context.Context, arg SetUserTOTPSecretParams) error
	// tenancy: root (called after the key was verified)
	TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error
	// tenancy: root (the gateway acts for a verified agent)
	TouchAgent(ctx context.Context, arg TouchAgentParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	TouchSessionSeen(ctx context.Context, arg TouchSessionSeenParams) error
	// tenancy: org
	UpdateAgentLabels(ctx context.Context, arg UpdateAgentLabelsParams) (Agent, error)
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error)
	UpdateMaintenance(ctx context.Context, arg UpdateMaintenanceParams) (Maintenance, error)
	UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error)
	UpdateMonitorState(ctx context.Context, arg UpdateMonitorStateParams) error
	UpdateOrgName(ctx context.Context, arg UpdateOrgNameParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) error
	UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error)
	UpdateStatusPage(ctx context.Context, arg UpdateStatusPageParams) (StatusPage, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpsertMembership(ctx context.Context, arg UpsertMembershipParams) error
	// tenancy: root (the link's token establishes the org; the row must still be open)
	UseInvite(ctx context.Context, arg UseInviteParams) (int64, error)
	UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error)
	// tenancy: root (the link's token establishes the user)
	UseResetToken(ctx context.Context, arg UseResetTokenParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
