// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AckIncident(ctx context.Context, arg AckIncidentParams) (int64, error)
	// tenancy: root (dispatcher keeps per-monitor order)
	CountEarlierPendingDeliveries(ctx context.Context, arg CountEarlierPendingDeliveriesParams) (int64, error)
	CountMonitorsByState(ctx context.Context, projectID string) ([]CountMonitorsByStateRow, error)
	// tenancy: org (quota check)
	CountMonitorsInOrg(ctx context.Context, orgID string) (int64, error)
	CountOpenIncidents(ctx context.Context, projectID string) (int64, error)
	CountOrgs(ctx context.Context) (int64, error)
	CountProjects(ctx context.Context, orgID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error)
	CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// tenancy: root (retention job)
	DeleteBodiesBefore(ctx context.Context, createdAt int64) (int64, error)
	DeleteChannel(ctx context.Context, arg DeleteChannelParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context, expiresAt int64) (int64, error)
	DeleteHeaderMembershipsForUser(ctx context.Context, userID string) error
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) (int64, error)
	DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) (int64, error)
	// tenancy: root (retention job)
	DeleteObservationsBefore(ctx context.Context, at int64) (int64, error)
	DeleteOrg(ctx context.Context, id string) (int64, error)
	DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error)
	DeleteRoute(ctx context.Context, arg DeleteRouteParams) (int64, error)
	DeleteSession(ctx context.Context, id string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error)
	GetBody(ctx context.Context, arg GetBodyParams) (Body, error)
	GetChannel(ctx context.Context, arg GetChannelParams) (Channel, error)
	GetChannelByName(ctx context.Context, arg GetChannelByNameParams) (Channel, error)
	GetEvent(ctx context.Context, arg GetEventParams) (Event, error)
	GetIncident(ctx context.Context, arg GetIncidentParams) (Incident, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetMonitor(ctx context.Context, arg GetMonitorParams) (Monitor, error)
	// tenancy: root (scheduler reload after a bus event)
	GetMonitorByID(ctx context.Context, id string) (Monitor, error)
	GetMonitorBySlug(ctx context.Context, arg GetMonitorBySlugParams) (Monitor, error)
	GetObservation(ctx context.Context, arg GetObservationParams) (Observation, error)
	GetOpenIncidentForMonitor(ctx context.Context, arg GetOpenIncidentForMonitorParams) (Incident, error)
	GetOrg(ctx context.Context, id string) (Org, error)
	GetOrgBySlug(ctx context.Context, slug string) (Org, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	// tenancy: root (auth establishes the scope from an API key's project id)
	GetProjectByID(ctx context.Context, id string) (Project, error)
	// tenancy: root (ping ingress resolves the project from the key)
	GetProjectByPingKey(ctx context.Context, arg GetProjectByPingKeyParams) (Project, error)
	GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error)
	GetRoute(ctx context.Context, arg GetRouteParams) (Route, error)
	GetSession(ctx context.Context, arg GetSessionParams) (Session, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserBySubject(ctx context.Context, subject string) (User, error)
	InsertBody(ctx context.Context, arg InsertBodyParams) error
	InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertObservation(ctx context.Context, arg InsertObservationParams) error
	// tenancy: root (dispatcher, repeat_every)
	LastDeliveryForRoute(ctx context.Context, arg LastDeliveryForRouteParams) (Delivery, error)
	LastObservation(ctx context.Context, arg LastObservationParams) (Observation, error)
	ListAPIKeys(ctx context.Context, projectID string) ([]ApiKey, error)
	// tenancy: root (bearer lookup establishes the scope)
	ListAPIKeysByPrefix(ctx context.Context, prefix string) ([]ApiKey, error)
	// tenancy: root (instance admin)
	ListAllProjects(ctx context.Context) ([]ListAllProjectsRow, error)
	ListChannels(ctx context.Context, projectID string) ([]Channel, error)
	ListDeliveriesForEvent(ctx context.Context, arg ListDeliveriesForEventParams) ([]Delivery, error)
	// tenancy: root (dispatcher)
	ListDueDeliveries(ctx context.Context, arg ListDueDeliveriesParams) ([]Delivery, error)
	// tenancy: root (scheduler)
	ListDueMonitors(ctx context.Context, arg ListDueMonitorsParams) ([]Monitor, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListEventsSince(ctx context.Context, arg ListEventsSinceParams) ([]Event, error)
	ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]ListIncidentsRow, error)
	ListMembershipsForOrg(ctx context.Context, orgID string) ([]ListMembershipsForOrgRow, error)
	ListMembershipsForUser(ctx context.Context, userID string) ([]ListMembershipsForUserRow, error)
	ListMonitors(ctx context.Context, projectID string) ([]Monitor, error)
	ListObservations(ctx context.Context, arg ListObservationsParams) ([]Observation, error)
	ListObservationsSince(ctx context.Context, arg ListObservationsSinceParams) ([]Observation, error)
	ListOpenIncidents(ctx context.Context, projectID string) ([]ListOpenIncidentsRow, error)
	ListOrgs(ctx context.Context) ([]Org, error)
	ListProjectEvents(ctx context.Context, arg ListProjectEventsParams) ([]ListProjectEventsRow, error)
	ListProjects(ctx context.Context, orgID string) ([]Project, error)
	// tenancy: root (the user's memberships are the scope)
	ListProjectsForUser(ctx context.Context, userID string) ([]ListProjectsForUserRow, error)
	ListRecentDeliveries(ctx context.Context, arg ListRecentDeliveriesParams) ([]ListRecentDeliveriesRow, error)
	ListRoutes(ctx context.Context, projectID string) ([]ListRoutesRow, error)
	// tenancy: root (scheduler, max_runtime)
	ListRunningMonitors(ctx context.Context, runStartedAt *int64) ([]Monitor, error)
	ListUsers(ctx context.Context) ([]User, error)
	// tenancy: root (dispatcher)
	MarkDeliveryDelivered(ctx context.Context, arg MarkDeliveryDeliveredParams) error
	// tenancy: root (dispatcher)
	MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error
	// tenancy: root (scheduler)
	NextDueAt(ctx context.Context) (int64, error)
	OpenIncident(ctx context.Context, arg OpenIncidentParams) (Incident, error)
	// tenancy: root (dispatcher)
	RescheduleDelivery(ctx context.Context, arg RescheduleDeliveryParams) error
	ResolveIncident(ctx context.Context, arg ResolveIncidentParams) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	RotatePingKey(ctx context.Context, arg RotatePingKeyParams) error
	SetInstanceAdmin(ctx context.Context, arg SetInstanceAdminParams) (int64, error)
	SetMonitorPaused(ctx context.Context, arg SetMonitorPausedParams) error
	SetOrgQuotas(ctx context.Context, arg SetOrgQuotasParams) error
	SetSessionProject(ctx context.Context, arg SetSessionProjectParams) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	// tenancy: root (called after the key was verified)
	TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error)
	UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error)
	UpdateMonitorState(ctx context.Context, arg UpdateMonitorStateParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) error
	UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpsertMembership(ctx context.Context, arg UpsertMembershipParams) error
}

var _ Querier = (*Queries)(nil)
