// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"
)

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (id, project_id, match_tags, channel_id, on_states, repeat_every_s, priority, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, match_tags, channel_id, on_states, repeat_every_s, priority, created_at, updated_at
`

type CreateRouteParams struct {
	ID           string
	ProjectID    string
	MatchTags    string
	ChannelID    string
	OnStates     string
	RepeatEveryS int64
	Priority     int64
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, createRoute,
		arg.ID,
		arg.ProjectID,
		arg.MatchTags,
		arg.ChannelID,
		arg.OnStates,
		arg.RepeatEveryS,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MatchTags,
		&i.ChannelID,
		&i.OnStates,
		&i.RepeatEveryS,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoute = `-- name: DeleteRoute :execrows
DELETE FROM routes WHERE project_id = ? AND id = ?
`

type DeleteRouteParams struct {
	ProjectID string
	ID        string
}

func (q *Queries) DeleteRoute(ctx context.Context, arg DeleteRouteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRoute, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRoute = `-- name: GetRoute :one
SELECT id, project_id, match_tags, channel_id, on_states, repeat_every_s, priority, created_at, updated_at FROM routes WHERE project_id = ? AND id = ?
`

type GetRouteParams struct {
	ProjectID string
	ID        string
}

func (q *Queries) GetRoute(ctx context.Context, arg GetRouteParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRoute, arg.ProjectID, arg.ID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MatchTags,
		&i.ChannelID,
		&i.OnStates,
		&i.RepeatEveryS,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoutes = `-- name: ListRoutes :many
SELECT r.id, r.project_id, r.match_tags, r.channel_id, r.on_states, r.repeat_every_s, r.priority, r.created_at, r.updated_at, c.name AS channel_name, c.kind AS channel_kind, c.enabled AS channel_enabled
FROM routes r JOIN channels c ON c.id = r.channel_id
WHERE r.project_id = ?
ORDER BY r.priority DESC, r.created_at, r.id
`

type ListRoutesRow struct {
	ID             string
	ProjectID      string
	MatchTags      string
	ChannelID      string
	OnStates       string
	RepeatEveryS   int64
	Priority       int64
	CreatedAt      int64
	UpdatedAt      int64
	ChannelName    string
	ChannelKind    string
	ChannelEnabled bool
}

func (q *Queries) ListRoutes(ctx context.Context, projectID string) ([]ListRoutesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoutes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoutesRow
	for rows.Next() {
		var i ListRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MatchTags,
			&i.ChannelID,
			&i.OnStates,
			&i.RepeatEveryS,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelName,
			&i.ChannelKind,
			&i.ChannelEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE routes
SET match_tags = ?, channel_id = ?, on_states = ?, repeat_every_s = ?, priority = ?, updated_at = ?
WHERE project_id = ? AND id = ?
RETURNING id, project_id, match_tags, channel_id, on_states, repeat_every_s, priority, created_at, updated_at
`

type UpdateRouteParams struct {
	MatchTags    string
	ChannelID    string
	OnStates     string
	RepeatEveryS int64
	Priority     int64
	UpdatedAt    int64
	ProjectID    string
	ID           string
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, updateRoute,
		arg.MatchTags,
		arg.ChannelID,
		arg.OnStates,
		arg.RepeatEveryS,
		arg.Priority,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.ID,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MatchTags,
		&i.ChannelID,
		&i.OnStates,
		&i.RepeatEveryS,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
