// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"
)

const countRoutesForChannel = `-- name: CountRoutesForChannel :one
SELECT COUNT(*) FROM route_channels WHERE project_id = ? AND channel_id = ?
`

type CountRoutesForChannelParams struct {
	ProjectID string
	ChannelID string
}

func (q *Queries) CountRoutesForChannel(ctx context.Context, arg CountRoutesForChannelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoutesForChannel, arg.ProjectID, arg.ChannelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (id, project_id, match_tags, on_states, repeat_every_s, priority, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, match_tags, on_states, repeat_every_s, priority, created_at, updated_at
`

type CreateRouteParams struct {
	ID           string
	ProjectID    string
	MatchTags    string
	OnStates     string
	RepeatEveryS int64
	Priority     int64
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, createRoute,
		arg.ID,
		arg.ProjectID,
		arg.MatchTags,
		arg.OnStates,
		arg.RepeatEveryS,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MatchTags,
		&i.OnStates,
		&i.RepeatEveryS,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrphanRoutes = `-- name: DeleteOrphanRoutes :execrows
DELETE FROM routes WHERE routes.project_id = ? AND NOT EXISTS (SELECT 1 FROM route_channels rc WHERE rc.route_id = routes.id)
`

func (q *Queries) DeleteOrphanRoutes(ctx context.Context, projectID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrphanRoutes, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRoute = `-- name: DeleteRoute :execrows
DELETE FROM routes WHERE project_id = ? AND id = ?
`

type DeleteRouteParams struct {
	ProjectID string
	ID        string
}

func (q *Queries) DeleteRoute(ctx context.Context, arg DeleteRouteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRoute, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRouteChannels = `-- name: DeleteRouteChannels :exec
DELETE FROM route_channels WHERE project_id = ? AND route_id = ?
`

type DeleteRouteChannelsParams struct {
	ProjectID string
	RouteID   string
}

func (q *Queries) DeleteRouteChannels(ctx context.Context, arg DeleteRouteChannelsParams) error {
	_, err := q.db.ExecContext(ctx, deleteRouteChannels, arg.ProjectID, arg.RouteID)
	return err
}

const getRoute = `-- name: GetRoute :one
SELECT id, project_id, match_tags, on_states, repeat_every_s, priority, created_at, updated_at FROM routes WHERE project_id = ? AND id = ?
`

type GetRouteParams struct {
	ProjectID string
	ID        string
}

func (q *Queries) GetRoute(ctx context.Context, arg GetRouteParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRoute, arg.ProjectID, arg.ID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MatchTags,
		&i.OnStates,
		&i.RepeatEveryS,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRouteChannel = `-- name: InsertRouteChannel :exec
INSERT INTO route_channels (route_id, channel_id, project_id) VALUES (?, ?, ?)
`

type InsertRouteChannelParams struct {
	RouteID   string
	ChannelID string
	ProjectID string
}

func (q *Queries) InsertRouteChannel(ctx context.Context, arg InsertRouteChannelParams) error {
	_, err := q.db.ExecContext(ctx, insertRouteChannel, arg.RouteID, arg.ChannelID, arg.ProjectID)
	return err
}

const listRouteChannels = `-- name: ListRouteChannels :many
SELECT rc.route_id, c.id AS channel_id, c.name AS channel_name, c.kind AS channel_kind, c.enabled AS channel_enabled
FROM route_channels rc JOIN channels c ON c.id = rc.channel_id
WHERE rc.project_id = ?
ORDER BY rc.route_id, c.name
`

type ListRouteChannelsRow struct {
	RouteID        string
	ChannelID      string
	ChannelName    string
	ChannelKind    string
	ChannelEnabled bool
}

func (q *Queries) ListRouteChannels(ctx context.Context, projectID string) ([]ListRouteChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRouteChannels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouteChannelsRow
	for rows.Next() {
		var i ListRouteChannelsRow
		if err := rows.Scan(
			&i.RouteID,
			&i.ChannelID,
			&i.ChannelName,
			&i.ChannelKind,
			&i.ChannelEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, project_id, match_tags, on_states, repeat_every_s, priority, created_at, updated_at FROM routes WHERE project_id = ? ORDER BY priority DESC, created_at, id
`

func (q *Queries) ListRoutes(ctx context.Context, projectID string) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listRoutes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.MatchTags,
			&i.OnStates,
			&i.RepeatEveryS,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE routes
SET match_tags = ?, on_states = ?, repeat_every_s = ?, priority = ?, updated_at = ?
WHERE project_id = ? AND id = ?
RETURNING id, project_id, match_tags, on_states, repeat_every_s, priority, created_at, updated_at
`

type UpdateRouteParams struct {
	MatchTags    string
	OnStates     string
	RepeatEveryS int64
	Priority     int64
	UpdatedAt    int64
	ProjectID    string
	ID           string
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, updateRoute,
		arg.MatchTags,
		arg.OnStates,
		arg.RepeatEveryS,
		arg.Priority,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.ID,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.MatchTags,
		&i.OnStates,
		&i.RepeatEveryS,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
