// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, csrf, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string
	UserID    string
	Csrf      string
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Csrf,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, csrf, created_at, expires_at, last_project_id, user_agent, ip, last_seen_at FROM sessions WHERE id = ? AND expires_at > ?
`

type GetSessionParams struct {
	ID        string
	ExpiresAt int64
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.ID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Csrf,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastProjectID,
		&i.UserAgent,
		&i.Ip,
		&i.LastSeenAt,
	)
	return i, err
}

const setSessionProject = `-- name: SetSessionProject :exec
UPDATE sessions SET last_project_id = ? WHERE id = ?
`

type SetSessionProjectParams struct {
	LastProjectID *string
	ID            string
}

func (q *Queries) SetSessionProject(ctx context.Context, arg SetSessionProjectParams) error {
	_, err := q.db.ExecContext(ctx, setSessionProject, arg.LastProjectID, arg.ID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET expires_at = ? WHERE id = ?
`

type TouchSessionParams struct {
	ExpiresAt int64
	ID        string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.ExpiresAt, arg.ID)
	return err
}
