// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_pages.sql

package db

import (
	"context"
)

const createStatusPage = `-- name: CreateStatusPage :one
INSERT INTO status_pages (id, project_id, slug, title, match_tags, public, password_hash, custom_domain, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, slug, title, match_tags, public, password_hash, custom_domain, created_at, updated_at
`

type CreateStatusPageParams struct {
	ID           string
	ProjectID    string
	Slug         string
	Title        string
	MatchTags    string
	Public       bool
	PasswordHash *string
	CustomDomain *string
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) CreateStatusPage(ctx context.Context, arg CreateStatusPageParams) (StatusPage, error) {
	row := q.db.QueryRowContext(ctx, createStatusPage,
		arg.ID,
		arg.ProjectID,
		arg.Slug,
		arg.Title,
		arg.MatchTags,
		arg.Public,
		arg.PasswordHash,
		arg.CustomDomain,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.MatchTags,
		&i.Public,
		&i.PasswordHash,
		&i.CustomDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStatusPage = `-- name: DeleteStatusPage :execrows
DELETE FROM status_pages WHERE project_id = ? AND slug = ?
`

type DeleteStatusPageParams struct {
	ProjectID string
	Slug      string
}

func (q *Queries) DeleteStatusPage(ctx context.Context, arg DeleteStatusPageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStatusPage, arg.ProjectID, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getStatusPage = `-- name: GetStatusPage :one
SELECT id, project_id, slug, title, match_tags, public, password_hash, custom_domain, created_at, updated_at FROM status_pages WHERE project_id = ? AND slug = ?
`

type GetStatusPageParams struct {
	ProjectID string
	Slug      string
}

func (q *Queries) GetStatusPage(ctx context.Context, arg GetStatusPageParams) (StatusPage, error) {
	row := q.db.QueryRowContext(ctx, getStatusPage, arg.ProjectID, arg.Slug)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.MatchTags,
		&i.Public,
		&i.PasswordHash,
		&i.CustomDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatusPageByDomain = `-- name: GetStatusPageByDomain :one
SELECT id, project_id, slug, title, match_tags, public, password_hash, custom_domain, created_at, updated_at FROM status_pages WHERE custom_domain = ?
`

// tenancy: root (public page served on its custom domain)
func (q *Queries) GetStatusPageByDomain(ctx context.Context, customDomain *string) (StatusPage, error) {
	row := q.db.QueryRowContext(ctx, getStatusPageByDomain, customDomain)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.MatchTags,
		&i.Public,
		&i.PasswordHash,
		&i.CustomDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatusPageBySlug = `-- name: GetStatusPageBySlug :one
SELECT id, project_id, slug, title, match_tags, public, password_hash, custom_domain, created_at, updated_at FROM status_pages WHERE slug = ?
`

// tenancy: root (public page: the slug is unique per instance)
func (q *Queries) GetStatusPageBySlug(ctx context.Context, slug string) (StatusPage, error) {
	row := q.db.QueryRowContext(ctx, getStatusPageBySlug, slug)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.MatchTags,
		&i.Public,
		&i.PasswordHash,
		&i.CustomDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStatusPages = `-- name: ListStatusPages :many
SELECT id, project_id, slug, title, match_tags, public, password_hash, custom_domain, created_at, updated_at FROM status_pages WHERE project_id = ? ORDER BY title, id
`

func (q *Queries) ListStatusPages(ctx context.Context, projectID string) ([]StatusPage, error) {
	rows, err := q.db.QueryContext(ctx, listStatusPages, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatusPage
	for rows.Next() {
		var i StatusPage
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Title,
			&i.MatchTags,
			&i.Public,
			&i.PasswordHash,
			&i.CustomDomain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatusPage = `-- name: UpdateStatusPage :one
UPDATE status_pages
SET slug = ?, title = ?, match_tags = ?, public = ?, password_hash = ?, custom_domain = ?, updated_at = ?
WHERE project_id = ? AND id = ?
RETURNING id, project_id, slug, title, match_tags, public, password_hash, custom_domain, created_at, updated_at
`

type UpdateStatusPageParams struct {
	Slug         string
	Title        string
	MatchTags    string
	Public       bool
	PasswordHash *string
	CustomDomain *string
	UpdatedAt    int64
	ProjectID    string
	ID           string
}

func (q *Queries) UpdateStatusPage(ctx context.Context, arg UpdateStatusPageParams) (StatusPage, error) {
	row := q.db.QueryRowContext(ctx, updateStatusPage,
		arg.Slug,
		arg.Title,
		arg.MatchTags,
		arg.Public,
		arg.PasswordHash,
		arg.CustomDomain,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.ID,
	)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.MatchTags,
		&i.Public,
		&i.PasswordHash,
		&i.CustomDomain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
