// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const countActiveInstanceAdmins = `-- name: CountActiveInstanceAdmins :one
SELECT COUNT(*) FROM users WHERE is_instance_admin = 1 AND disabled_at IS NULL
`

func (q *Queries) CountActiveInstanceAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveInstanceAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResetToken = `-- name: CreateResetToken :exec
INSERT INTO reset_tokens (id, user_id, token_hash, created_by, created_at, expires_at) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateResetTokenParams struct {
	ID        string
	UserID    string
	TokenHash string
	CreatedBy *string
	CreatedAt int64
	ExpiresAt int64
}

// tenancy: root (instance admin)
func (q *Queries) CreateResetToken(ctx context.Context, arg CreateResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, createResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, subject, email, display_name, password_hash, is_instance_admin, source, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, subject, email, display_name, password_hash, is_instance_admin, created_at, source, disabled_at, disabled_by, totp_secret, totp_enabled_at, totp_last_step, password_changed_at
`

type CreateUserParams struct {
	ID              string
	Subject         string
	Email           string
	DisplayName     string
	PasswordHash    *string
	IsInstanceAdmin bool
	Source          string
	CreatedAt       int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Subject,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsInstanceAdmin,
		arg.Source,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsInstanceAdmin,
		&i.CreatedAt,
		&i.Source,
		&i.DisabledAt,
		&i.DisabledBy,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.PasswordChangedAt,
	)
	return i, err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM recovery_codes WHERE user_id = ?
`

// tenancy: root (follows the user)
func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryCodes, userID)
	return err
}

const getResetTokenByHash = `-- name: GetResetTokenByHash :one
SELECT r.id, r.user_id, r.token_hash, r.created_by, r.created_at, r.expires_at, r.used_at, u.subject, u.display_name, c.subject AS created_by_subject, c.display_name AS created_by_name
FROM reset_tokens r JOIN users u ON u.id = r.user_id LEFT JOIN users c ON c.id = r.created_by
WHERE r.token_hash = ?
`

type GetResetTokenByHashRow struct {
	ID               string
	UserID           string
	TokenHash        string
	CreatedBy        *string
	CreatedAt        int64
	ExpiresAt        int64
	UsedAt           *int64
	Subject          string
	DisplayName      string
	CreatedBySubject *string
	CreatedByName    *string
}

// tenancy: root (the link's token establishes the user)
func (q *Queries) GetResetTokenByHash(ctx context.Context, tokenHash string) (GetResetTokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getResetTokenByHash, tokenHash)
	var i GetResetTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Subject,
		&i.DisplayName,
		&i.CreatedBySubject,
		&i.CreatedByName,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, subject, email, display_name, password_hash, is_instance_admin, created_at, source, disabled_at, disabled_by, totp_secret, totp_enabled_at, totp_last_step, password_changed_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsInstanceAdmin,
		&i.CreatedAt,
		&i.Source,
		&i.DisabledAt,
		&i.DisabledBy,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUserBySubject = `-- name: GetUserBySubject :one
SELECT id, subject, email, display_name, password_hash, is_instance_admin, created_at, source, disabled_at, disabled_by, totp_secret, totp_enabled_at, totp_last_step, password_changed_at FROM users WHERE subject = ?
`

func (q *Queries) GetUserBySubject(ctx context.Context, subject string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySubject, subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsInstanceAdmin,
		&i.CreatedAt,
		&i.Source,
		&i.DisabledAt,
		&i.DisabledBy,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.PasswordChangedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, subject, email, display_name, password_hash, is_instance_admin, created_at, source, disabled_at, disabled_by, totp_secret, totp_enabled_at, totp_last_step, password_changed_at FROM users ORDER BY subject
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.IsInstanceAdmin,
			&i.CreatedAt,
			&i.Source,
			&i.DisabledAt,
			&i.DisabledBy,
			&i.TotpSecret,
			&i.TotpEnabledAt,
			&i.TotpLastStep,
			&i.PasswordChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithSeen = `-- name: ListUsersWithSeen :many
SELECT u.id, u.subject, u.email, u.display_name, u.password_hash, u.is_instance_admin, u.created_at, u.source, u.disabled_at, u.disabled_by, u.totp_secret, u.totp_enabled_at, u.totp_last_step, u.password_changed_at, (SELECT MAX(s.last_seen_at) FROM sessions s WHERE s.user_id = u.id) AS last_seen_at
FROM users u ORDER BY u.subject
`

type ListUsersWithSeenRow struct {
	ID                string
	Subject           string
	Email             string
	DisplayName       string
	PasswordHash      *string
	IsInstanceAdmin   bool
	CreatedAt         int64
	Source            string
	DisabledAt        *int64
	DisabledBy        *string
	TotpSecret        *string
	TotpEnabledAt     *int64
	TotpLastStep      int64
	PasswordChangedAt *int64
	LastSeenAt        interface{}
}

// tenancy: root (instance admin)
func (q *Queries) ListUsersWithSeen(ctx context.Context) ([]ListUsersWithSeenRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersWithSeen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithSeenRow
	for rows.Next() {
		var i ListUsersWithSeenRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.IsInstanceAdmin,
			&i.CreatedAt,
			&i.Source,
			&i.DisabledAt,
			&i.DisabledBy,
			&i.TotpSecret,
			&i.TotpEnabledAt,
			&i.TotpLastStep,
			&i.PasswordChangedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetUserTOTP = `-- name: ResetUserTOTP :exec
UPDATE users SET totp_secret = NULL, totp_enabled_at = NULL, totp_last_step = 0 WHERE id = ?
`

// tenancy: root (instance admin, or the account itself)
func (q *Queries) ResetUserTOTP(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, resetUserTOTP, id)
	return err
}

const setInstanceAdmin = `-- name: SetInstanceAdmin :execrows
UPDATE users SET is_instance_admin = ? WHERE id = ?
`

type SetInstanceAdminParams struct {
	IsInstanceAdmin bool
	ID              string
}

func (q *Queries) SetInstanceAdmin(ctx context.Context, arg SetInstanceAdminParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setInstanceAdmin, arg.IsInstanceAdmin, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUserDisabled = `-- name: SetUserDisabled :exec
UPDATE users SET disabled_at = ?, disabled_by = ? WHERE id = ?
`

type SetUserDisabledParams struct {
	DisabledAt *int64
	DisabledBy *string
	ID         string
}

// tenancy: root (instance admin)
func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error {
	_, err := q.db.ExecContext(ctx, setUserDisabled, arg.DisabledAt, arg.DisabledBy, arg.ID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type SetUserPasswordParams struct {
	PasswordHash *string
	ID           string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const setUserSource = `-- name: SetUserSource :exec
UPDATE users SET source = ? WHERE id = ?
`

type SetUserSourceParams struct {
	Source string
	ID     string
}

func (q *Queries) SetUserSource(ctx context.Context, arg SetUserSourceParams) error {
	_, err := q.db.ExecContext(ctx, setUserSource, arg.Source, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET email = ?, display_name = ? WHERE id = ?
`

type UpdateUserProfileParams struct {
	Email       string
	DisplayName string
	ID          string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile, arg.Email, arg.DisplayName, arg.ID)
	return err
}

const useResetToken = `-- name: UseResetToken :execrows
UPDATE reset_tokens SET used_at = ? WHERE id = ? AND used_at IS NULL AND expires_at > ?
`

type UseResetTokenParams struct {
	UsedAt    *int64
	ID        string
	ExpiresAt int64
}

// tenancy: root (the link's token establishes the user)
func (q *Queries) UseResetToken(ctx context.Context, arg UseResetTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useResetToken, arg.UsedAt, arg.ID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
