// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, subject, email, display_name, password_hash, is_instance_admin, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, subject, email, display_name, password_hash, is_instance_admin, created_at, source, disabled_at, disabled_by, totp_secret, totp_enabled_at, totp_last_step, password_changed_at
`

type CreateUserParams struct {
	ID              string
	Subject         string
	Email           string
	DisplayName     string
	PasswordHash    *string
	IsInstanceAdmin bool
	CreatedAt       int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Subject,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsInstanceAdmin,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsInstanceAdmin,
		&i.CreatedAt,
		&i.Source,
		&i.DisabledAt,
		&i.DisabledBy,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, subject, email, display_name, password_hash, is_instance_admin, created_at, source, disabled_at, disabled_by, totp_secret, totp_enabled_at, totp_last_step, password_changed_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsInstanceAdmin,
		&i.CreatedAt,
		&i.Source,
		&i.DisabledAt,
		&i.DisabledBy,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUserBySubject = `-- name: GetUserBySubject :one
SELECT id, subject, email, display_name, password_hash, is_instance_admin, created_at, source, disabled_at, disabled_by, totp_secret, totp_enabled_at, totp_last_step, password_changed_at FROM users WHERE subject = ?
`

func (q *Queries) GetUserBySubject(ctx context.Context, subject string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySubject, subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsInstanceAdmin,
		&i.CreatedAt,
		&i.Source,
		&i.DisabledAt,
		&i.DisabledBy,
		&i.TotpSecret,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.PasswordChangedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, subject, email, display_name, password_hash, is_instance_admin, created_at, source, disabled_at, disabled_by, totp_secret, totp_enabled_at, totp_last_step, password_changed_at FROM users ORDER BY subject
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.IsInstanceAdmin,
			&i.CreatedAt,
			&i.Source,
			&i.DisabledAt,
			&i.DisabledBy,
			&i.TotpSecret,
			&i.TotpEnabledAt,
			&i.TotpLastStep,
			&i.PasswordChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInstanceAdmin = `-- name: SetInstanceAdmin :execrows
UPDATE users SET is_instance_admin = ? WHERE id = ?
`

type SetInstanceAdminParams struct {
	IsInstanceAdmin bool
	ID              string
}

func (q *Queries) SetInstanceAdmin(ctx context.Context, arg SetInstanceAdminParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setInstanceAdmin, arg.IsInstanceAdmin, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type SetUserPasswordParams struct {
	PasswordHash *string
	ID           string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users SET email = ?, display_name = ? WHERE id = ?
`

type UpdateUserProfileParams struct {
	Email       string
	DisplayName string
	ID          string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile, arg.Email, arg.DisplayName, arg.ID)
	return err
}
